// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: request.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package protocol;

@kotlin.jvm.JvmName("-initializeastRequest")
public inline fun astRequest(block: protocol.AstRequestKt.Dsl.() -> kotlin.Unit): protocol.Request.AstRequest =
  protocol.AstRequestKt.Dsl._create(protocol.Request.AstRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `protocol.AstRequest`
 */
public object AstRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: protocol.Request.AstRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: protocol.Request.AstRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): protocol.Request.AstRequest = _builder.build()

    /**
     * `string code = 1;`
     */
    public var code: kotlin.String
      @JvmName("getCode")
      get() = _builder.getCode()
      @JvmName("setCode")
      set(value) {
        _builder.setCode(value)
      }
    /**
     * `string code = 1;`
     */
    public fun clearCode() {
      _builder.clearCode()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun protocol.Request.AstRequest.copy(block: `protocol`.AstRequestKt.Dsl.() -> kotlin.Unit): protocol.Request.AstRequest =
  `protocol`.AstRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

