// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: expressions.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package protocol;

@kotlin.jvm.JvmName("-initializeboolLit")
public inline fun boolLit(block: protocol.BoolLitKt.Dsl.() -> kotlin.Unit): protocol.Expressions.BoolLit =
  protocol.BoolLitKt.Dsl._create(protocol.Expressions.BoolLit.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `protocol.BoolLit`
 */
public object BoolLitKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: protocol.Expressions.BoolLit.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: protocol.Expressions.BoolLit.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): protocol.Expressions.BoolLit = _builder.build()

    /**
     * `string value = 1;`
     */
    public var value: kotlin.String
      @JvmName("getValue")
      get() = _builder.getValue()
      @JvmName("setValue")
      set(value) {
        _builder.setValue(value)
      }
    /**
     * `string value = 1;`
     */
    public fun clearValue() {
      _builder.clearValue()
    }

    /**
     * `.protocol.Position position = 2;`
     */
    public var position: protocol.PositionOuterClass.Position
      @JvmName("getPosition")
      get() = _builder.getPosition()
      @JvmName("setPosition")
      set(value) {
        _builder.setPosition(value)
      }
    /**
     * `.protocol.Position position = 2;`
     */
    public fun clearPosition() {
      _builder.clearPosition()
    }
    /**
     * `.protocol.Position position = 2;`
     * @return Whether the position field is set.
     */
    public fun hasPosition(): kotlin.Boolean {
      return _builder.hasPosition()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun protocol.Expressions.BoolLit.copy(block: `protocol`.BoolLitKt.Dsl.() -> kotlin.Unit): protocol.Expressions.BoolLit =
  `protocol`.BoolLitKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val protocol.Expressions.BoolLitOrBuilder.positionOrNull: protocol.PositionOuterClass.Position?
  get() = if (hasPosition()) getPosition() else null

