// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: statements.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package protocol;

@kotlin.jvm.JvmName("-initializeclassDefinitionStatement")
public inline fun classDefinitionStatement(block: protocol.ClassDefinitionStatementKt.Dsl.() -> kotlin.Unit): protocol.Statements.ClassDefinitionStatement =
  protocol.ClassDefinitionStatementKt.Dsl._create(protocol.Statements.ClassDefinitionStatement.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `protocol.ClassDefinitionStatement`
 */
public object ClassDefinitionStatementKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: protocol.Statements.ClassDefinitionStatement.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: protocol.Statements.ClassDefinitionStatement.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): protocol.Statements.ClassDefinitionStatement = _builder.build()

    /**
     * `.protocol.EncapsulationType encapsulation = 1;`
     */
    public var encapsulation: protocol.Statements.EncapsulationType
      @JvmName("getEncapsulation")
      get() = _builder.getEncapsulation()
      @JvmName("setEncapsulation")
      set(value) {
        _builder.setEncapsulation(value)
      }
    public var encapsulationValue: kotlin.Int
      @JvmName("getEncapsulationValue")
      get() = _builder.getEncapsulationValue()
      @JvmName("setEncapsulationValue")
      set(value) {
        _builder.setEncapsulationValue(value)
      }
    /**
     * `.protocol.EncapsulationType encapsulation = 1;`
     */
    public fun clearEncapsulation() {
      _builder.clearEncapsulation()
    }

    /**
     * `string name = 2;`
     */
    public var name: kotlin.String
      @JvmName("getName")
      get() = _builder.getName()
      @JvmName("setName")
      set(value) {
        _builder.setName(value)
      }
    /**
     * `string name = 2;`
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * `string parentName = 3;`
     */
    public var parentName: kotlin.String
      @JvmName("getParentName")
      get() = _builder.getParentName()
      @JvmName("setParentName")
      set(value) {
        _builder.setParentName(value)
      }
    /**
     * `string parentName = 3;`
     */
    public fun clearParentName() {
      _builder.clearParentName()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class PropertiesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .protocol.PropertyDeclaration properties = 4;`
     */
     public val properties: com.google.protobuf.kotlin.DslList<protocol.Statements.PropertyDeclaration, PropertiesProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getPropertiesList()
      )
    /**
     * `repeated .protocol.PropertyDeclaration properties = 4;`
     * @param value The properties to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addProperties")
    public fun com.google.protobuf.kotlin.DslList<protocol.Statements.PropertyDeclaration, PropertiesProxy>.add(value: protocol.Statements.PropertyDeclaration) {
      _builder.addProperties(value)
    }
    /**
     * `repeated .protocol.PropertyDeclaration properties = 4;`
     * @param value The properties to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignProperties")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<protocol.Statements.PropertyDeclaration, PropertiesProxy>.plusAssign(value: protocol.Statements.PropertyDeclaration) {
      add(value)
    }
    /**
     * `repeated .protocol.PropertyDeclaration properties = 4;`
     * @param values The properties to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllProperties")
    public fun com.google.protobuf.kotlin.DslList<protocol.Statements.PropertyDeclaration, PropertiesProxy>.addAll(values: kotlin.collections.Iterable<protocol.Statements.PropertyDeclaration>) {
      _builder.addAllProperties(values)
    }
    /**
     * `repeated .protocol.PropertyDeclaration properties = 4;`
     * @param values The properties to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllProperties")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<protocol.Statements.PropertyDeclaration, PropertiesProxy>.plusAssign(values: kotlin.collections.Iterable<protocol.Statements.PropertyDeclaration>) {
      addAll(values)
    }
    /**
     * `repeated .protocol.PropertyDeclaration properties = 4;`
     * @param index The index to set the value at.
     * @param value The properties to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setProperties")
    public operator fun com.google.protobuf.kotlin.DslList<protocol.Statements.PropertyDeclaration, PropertiesProxy>.set(index: kotlin.Int, value: protocol.Statements.PropertyDeclaration) {
      _builder.setProperties(index, value)
    }
    /**
     * `repeated .protocol.PropertyDeclaration properties = 4;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearProperties")
    public fun com.google.protobuf.kotlin.DslList<protocol.Statements.PropertyDeclaration, PropertiesProxy>.clear() {
      _builder.clearProperties()
    }


    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ConstructorsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .protocol.ConstructorDefinitionStatement constructors = 5;`
     */
     public val constructors: com.google.protobuf.kotlin.DslList<protocol.Statements.ConstructorDefinitionStatement, ConstructorsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getConstructorsList()
      )
    /**
     * `repeated .protocol.ConstructorDefinitionStatement constructors = 5;`
     * @param value The constructors to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addConstructors")
    public fun com.google.protobuf.kotlin.DslList<protocol.Statements.ConstructorDefinitionStatement, ConstructorsProxy>.add(value: protocol.Statements.ConstructorDefinitionStatement) {
      _builder.addConstructors(value)
    }
    /**
     * `repeated .protocol.ConstructorDefinitionStatement constructors = 5;`
     * @param value The constructors to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignConstructors")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<protocol.Statements.ConstructorDefinitionStatement, ConstructorsProxy>.plusAssign(value: protocol.Statements.ConstructorDefinitionStatement) {
      add(value)
    }
    /**
     * `repeated .protocol.ConstructorDefinitionStatement constructors = 5;`
     * @param values The constructors to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllConstructors")
    public fun com.google.protobuf.kotlin.DslList<protocol.Statements.ConstructorDefinitionStatement, ConstructorsProxy>.addAll(values: kotlin.collections.Iterable<protocol.Statements.ConstructorDefinitionStatement>) {
      _builder.addAllConstructors(values)
    }
    /**
     * `repeated .protocol.ConstructorDefinitionStatement constructors = 5;`
     * @param values The constructors to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllConstructors")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<protocol.Statements.ConstructorDefinitionStatement, ConstructorsProxy>.plusAssign(values: kotlin.collections.Iterable<protocol.Statements.ConstructorDefinitionStatement>) {
      addAll(values)
    }
    /**
     * `repeated .protocol.ConstructorDefinitionStatement constructors = 5;`
     * @param index The index to set the value at.
     * @param value The constructors to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setConstructors")
    public operator fun com.google.protobuf.kotlin.DslList<protocol.Statements.ConstructorDefinitionStatement, ConstructorsProxy>.set(index: kotlin.Int, value: protocol.Statements.ConstructorDefinitionStatement) {
      _builder.setConstructors(index, value)
    }
    /**
     * `repeated .protocol.ConstructorDefinitionStatement constructors = 5;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearConstructors")
    public fun com.google.protobuf.kotlin.DslList<protocol.Statements.ConstructorDefinitionStatement, ConstructorsProxy>.clear() {
      _builder.clearConstructors()
    }


    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class MethodsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .protocol.FunctionDefinitionStatement methods = 6;`
     */
     public val methods: com.google.protobuf.kotlin.DslList<protocol.Statements.FunctionDefinitionStatement, MethodsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getMethodsList()
      )
    /**
     * `repeated .protocol.FunctionDefinitionStatement methods = 6;`
     * @param value The methods to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addMethods")
    public fun com.google.protobuf.kotlin.DslList<protocol.Statements.FunctionDefinitionStatement, MethodsProxy>.add(value: protocol.Statements.FunctionDefinitionStatement) {
      _builder.addMethods(value)
    }
    /**
     * `repeated .protocol.FunctionDefinitionStatement methods = 6;`
     * @param value The methods to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignMethods")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<protocol.Statements.FunctionDefinitionStatement, MethodsProxy>.plusAssign(value: protocol.Statements.FunctionDefinitionStatement) {
      add(value)
    }
    /**
     * `repeated .protocol.FunctionDefinitionStatement methods = 6;`
     * @param values The methods to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllMethods")
    public fun com.google.protobuf.kotlin.DslList<protocol.Statements.FunctionDefinitionStatement, MethodsProxy>.addAll(values: kotlin.collections.Iterable<protocol.Statements.FunctionDefinitionStatement>) {
      _builder.addAllMethods(values)
    }
    /**
     * `repeated .protocol.FunctionDefinitionStatement methods = 6;`
     * @param values The methods to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllMethods")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<protocol.Statements.FunctionDefinitionStatement, MethodsProxy>.plusAssign(values: kotlin.collections.Iterable<protocol.Statements.FunctionDefinitionStatement>) {
      addAll(values)
    }
    /**
     * `repeated .protocol.FunctionDefinitionStatement methods = 6;`
     * @param index The index to set the value at.
     * @param value The methods to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setMethods")
    public operator fun com.google.protobuf.kotlin.DslList<protocol.Statements.FunctionDefinitionStatement, MethodsProxy>.set(index: kotlin.Int, value: protocol.Statements.FunctionDefinitionStatement) {
      _builder.setMethods(index, value)
    }
    /**
     * `repeated .protocol.FunctionDefinitionStatement methods = 6;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearMethods")
    public fun com.google.protobuf.kotlin.DslList<protocol.Statements.FunctionDefinitionStatement, MethodsProxy>.clear() {
      _builder.clearMethods()
    }


    /**
     * `.protocol.VariableValueType parentClassType = 7;`
     */
    public var parentClassType: protocol.Statements.VariableValueType
      @JvmName("getParentClassType")
      get() = _builder.getParentClassType()
      @JvmName("setParentClassType")
      set(value) {
        _builder.setParentClassType(value)
      }
    /**
     * `.protocol.VariableValueType parentClassType = 7;`
     */
    public fun clearParentClassType() {
      _builder.clearParentClassType()
    }
    /**
     * `.protocol.VariableValueType parentClassType = 7;`
     * @return Whether the parentClassType field is set.
     */
    public fun hasParentClassType(): kotlin.Boolean {
      return _builder.hasParentClassType()
    }

    /**
     * `.protocol.Position position = 8;`
     */
    public var position: protocol.PositionOuterClass.Position
      @JvmName("getPosition")
      get() = _builder.getPosition()
      @JvmName("setPosition")
      set(value) {
        _builder.setPosition(value)
      }
    /**
     * `.protocol.Position position = 8;`
     */
    public fun clearPosition() {
      _builder.clearPosition()
    }
    /**
     * `.protocol.Position position = 8;`
     * @return Whether the position field is set.
     */
    public fun hasPosition(): kotlin.Boolean {
      return _builder.hasPosition()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun protocol.Statements.ClassDefinitionStatement.copy(block: `protocol`.ClassDefinitionStatementKt.Dsl.() -> kotlin.Unit): protocol.Statements.ClassDefinitionStatement =
  `protocol`.ClassDefinitionStatementKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val protocol.Statements.ClassDefinitionStatementOrBuilder.parentClassTypeOrNull: protocol.Statements.VariableValueType?
  get() = if (hasParentClassType()) getParentClassType() else null

public val protocol.Statements.ClassDefinitionStatementOrBuilder.positionOrNull: protocol.PositionOuterClass.Position?
  get() = if (hasPosition()) getPosition() else null

