// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: statements.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package protocol;

@kotlin.jvm.JvmName("-initializeconstructorDefinitionStatement")
public inline fun constructorDefinitionStatement(block: protocol.ConstructorDefinitionStatementKt.Dsl.() -> kotlin.Unit): protocol.Statements.ConstructorDefinitionStatement =
  protocol.ConstructorDefinitionStatementKt.Dsl._create(protocol.Statements.ConstructorDefinitionStatement.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `protocol.ConstructorDefinitionStatement`
 */
public object ConstructorDefinitionStatementKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: protocol.Statements.ConstructorDefinitionStatement.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: protocol.Statements.ConstructorDefinitionStatement.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): protocol.Statements.ConstructorDefinitionStatement = _builder.build()

    /**
     * `string className = 1;`
     */
    public var className: kotlin.String
      @JvmName("getClassName")
      get() = _builder.getClassName()
      @JvmName("setClassName")
      set(value) {
        _builder.setClassName(value)
      }
    /**
     * `string className = 1;`
     */
    public fun clearClassName() {
      _builder.clearClassName()
    }

    /**
     * `string constructorName = 2;`
     */
    public var constructorName: kotlin.String
      @JvmName("getConstructorName")
      get() = _builder.getConstructorName()
      @JvmName("setConstructorName")
      set(value) {
        _builder.setConstructorName(value)
      }
    /**
     * `string constructorName = 2;`
     */
    public fun clearConstructorName() {
      _builder.clearConstructorName()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ParametersProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .protocol.Parameter parameters = 3;`
     */
     public val parameters: com.google.protobuf.kotlin.DslList<protocol.Statements.Parameter, ParametersProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getParametersList()
      )
    /**
     * `repeated .protocol.Parameter parameters = 3;`
     * @param value The parameters to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addParameters")
    public fun com.google.protobuf.kotlin.DslList<protocol.Statements.Parameter, ParametersProxy>.add(value: protocol.Statements.Parameter) {
      _builder.addParameters(value)
    }
    /**
     * `repeated .protocol.Parameter parameters = 3;`
     * @param value The parameters to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignParameters")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<protocol.Statements.Parameter, ParametersProxy>.plusAssign(value: protocol.Statements.Parameter) {
      add(value)
    }
    /**
     * `repeated .protocol.Parameter parameters = 3;`
     * @param values The parameters to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllParameters")
    public fun com.google.protobuf.kotlin.DslList<protocol.Statements.Parameter, ParametersProxy>.addAll(values: kotlin.collections.Iterable<protocol.Statements.Parameter>) {
      _builder.addAllParameters(values)
    }
    /**
     * `repeated .protocol.Parameter parameters = 3;`
     * @param values The parameters to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllParameters")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<protocol.Statements.Parameter, ParametersProxy>.plusAssign(values: kotlin.collections.Iterable<protocol.Statements.Parameter>) {
      addAll(values)
    }
    /**
     * `repeated .protocol.Parameter parameters = 3;`
     * @param index The index to set the value at.
     * @param value The parameters to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setParameters")
    public operator fun com.google.protobuf.kotlin.DslList<protocol.Statements.Parameter, ParametersProxy>.set(index: kotlin.Int, value: protocol.Statements.Parameter) {
      _builder.setParameters(index, value)
    }
    /**
     * `repeated .protocol.Parameter parameters = 3;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearParameters")
    public fun com.google.protobuf.kotlin.DslList<protocol.Statements.Parameter, ParametersProxy>.clear() {
      _builder.clearParameters()
    }


    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class BodyProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .protocol.Statement body = 4;`
     */
     public val body: com.google.protobuf.kotlin.DslList<protocol.Statements.Statement, BodyProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getBodyList()
      )
    /**
     * `repeated .protocol.Statement body = 4;`
     * @param value The body to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addBody")
    public fun com.google.protobuf.kotlin.DslList<protocol.Statements.Statement, BodyProxy>.add(value: protocol.Statements.Statement) {
      _builder.addBody(value)
    }
    /**
     * `repeated .protocol.Statement body = 4;`
     * @param value The body to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignBody")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<protocol.Statements.Statement, BodyProxy>.plusAssign(value: protocol.Statements.Statement) {
      add(value)
    }
    /**
     * `repeated .protocol.Statement body = 4;`
     * @param values The body to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllBody")
    public fun com.google.protobuf.kotlin.DslList<protocol.Statements.Statement, BodyProxy>.addAll(values: kotlin.collections.Iterable<protocol.Statements.Statement>) {
      _builder.addAllBody(values)
    }
    /**
     * `repeated .protocol.Statement body = 4;`
     * @param values The body to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllBody")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<protocol.Statements.Statement, BodyProxy>.plusAssign(values: kotlin.collections.Iterable<protocol.Statements.Statement>) {
      addAll(values)
    }
    /**
     * `repeated .protocol.Statement body = 4;`
     * @param index The index to set the value at.
     * @param value The body to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setBody")
    public operator fun com.google.protobuf.kotlin.DslList<protocol.Statements.Statement, BodyProxy>.set(index: kotlin.Int, value: protocol.Statements.Statement) {
      _builder.setBody(index, value)
    }
    /**
     * `repeated .protocol.Statement body = 4;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearBody")
    public fun com.google.protobuf.kotlin.DslList<protocol.Statements.Statement, BodyProxy>.clear() {
      _builder.clearBody()
    }


    /**
     * `.protocol.ThisConstructorDefinition thisConstructor = 5;`
     */
    public var thisConstructor: protocol.Statements.ThisConstructorDefinition
      @JvmName("getThisConstructor")
      get() = _builder.getThisConstructor()
      @JvmName("setThisConstructor")
      set(value) {
        _builder.setThisConstructor(value)
      }
    /**
     * `.protocol.ThisConstructorDefinition thisConstructor = 5;`
     */
    public fun clearThisConstructor() {
      _builder.clearThisConstructor()
    }
    /**
     * `.protocol.ThisConstructorDefinition thisConstructor = 5;`
     * @return Whether the thisConstructor field is set.
     */
    public fun hasThisConstructor(): kotlin.Boolean {
      return _builder.hasThisConstructor()
    }

    /**
     * `.protocol.Position position = 6;`
     */
    public var position: protocol.PositionOuterClass.Position
      @JvmName("getPosition")
      get() = _builder.getPosition()
      @JvmName("setPosition")
      set(value) {
        _builder.setPosition(value)
      }
    /**
     * `.protocol.Position position = 6;`
     */
    public fun clearPosition() {
      _builder.clearPosition()
    }
    /**
     * `.protocol.Position position = 6;`
     * @return Whether the position field is set.
     */
    public fun hasPosition(): kotlin.Boolean {
      return _builder.hasPosition()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun protocol.Statements.ConstructorDefinitionStatement.copy(block: `protocol`.ConstructorDefinitionStatementKt.Dsl.() -> kotlin.Unit): protocol.Statements.ConstructorDefinitionStatement =
  `protocol`.ConstructorDefinitionStatementKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val protocol.Statements.ConstructorDefinitionStatementOrBuilder.thisConstructorOrNull: protocol.Statements.ThisConstructorDefinition?
  get() = if (hasThisConstructor()) getThisConstructor() else null

public val protocol.Statements.ConstructorDefinitionStatementOrBuilder.positionOrNull: protocol.PositionOuterClass.Position?
  get() = if (hasPosition()) getPosition() else null

