// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: statements.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package protocol;

@kotlin.jvm.JvmName("-initializeexpressionDefinitionStatement")
public inline fun expressionDefinitionStatement(block: protocol.ExpressionDefinitionStatementKt.Dsl.() -> kotlin.Unit): protocol.Statements.ExpressionDefinitionStatement =
  protocol.ExpressionDefinitionStatementKt.Dsl._create(protocol.Statements.ExpressionDefinitionStatement.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `protocol.ExpressionDefinitionStatement`
 */
public object ExpressionDefinitionStatementKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: protocol.Statements.ExpressionDefinitionStatement.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: protocol.Statements.ExpressionDefinitionStatement.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): protocol.Statements.ExpressionDefinitionStatement = _builder.build()

    /**
     * `.protocol.Expression value = 1;`
     */
    public var value: protocol.Expressions.Expression
      @JvmName("getValue")
      get() = _builder.getValue()
      @JvmName("setValue")
      set(value) {
        _builder.setValue(value)
      }
    /**
     * `.protocol.Expression value = 1;`
     */
    public fun clearValue() {
      _builder.clearValue()
    }
    /**
     * `.protocol.Expression value = 1;`
     * @return Whether the value field is set.
     */
    public fun hasValue(): kotlin.Boolean {
      return _builder.hasValue()
    }

    /**
     * `optional .protocol.Position position = 2;`
     */
    public var position: protocol.PositionOuterClass.Position
      @JvmName("getPosition")
      get() = _builder.getPosition()
      @JvmName("setPosition")
      set(value) {
        _builder.setPosition(value)
      }
    /**
     * `optional .protocol.Position position = 2;`
     */
    public fun clearPosition() {
      _builder.clearPosition()
    }
    /**
     * `optional .protocol.Position position = 2;`
     * @return Whether the position field is set.
     */
    public fun hasPosition(): kotlin.Boolean {
      return _builder.hasPosition()
    }
    public val ExpressionDefinitionStatementKt.Dsl.positionOrNull: protocol.PositionOuterClass.Position?
      get() = _builder.positionOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun protocol.Statements.ExpressionDefinitionStatement.copy(block: `protocol`.ExpressionDefinitionStatementKt.Dsl.() -> kotlin.Unit): protocol.Statements.ExpressionDefinitionStatement =
  `protocol`.ExpressionDefinitionStatementKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val protocol.Statements.ExpressionDefinitionStatementOrBuilder.valueOrNull: protocol.Expressions.Expression?
  get() = if (hasValue()) getValue() else null

public val protocol.Statements.ExpressionDefinitionStatementOrBuilder.positionOrNull: protocol.PositionOuterClass.Position?
  get() = if (hasPosition()) getPosition() else null

