// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: statements.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package protocol;

@kotlin.jvm.JvmName("-initializeforDefinitionStatement")
public inline fun forDefinitionStatement(block: protocol.ForDefinitionStatementKt.Dsl.() -> kotlin.Unit): protocol.Statements.ForDefinitionStatement =
  protocol.ForDefinitionStatementKt.Dsl._create(protocol.Statements.ForDefinitionStatement.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `protocol.ForDefinitionStatement`
 */
public object ForDefinitionStatementKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: protocol.Statements.ForDefinitionStatement.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: protocol.Statements.ForDefinitionStatement.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): protocol.Statements.ForDefinitionStatement = _builder.build()

    /**
     * `.protocol.ForCondition forCondition = 1;`
     */
    public var forCondition: protocol.Statements.ForCondition
      @JvmName("getForCondition")
      get() = _builder.getForCondition()
      @JvmName("setForCondition")
      set(value) {
        _builder.setForCondition(value)
      }
    /**
     * `.protocol.ForCondition forCondition = 1;`
     */
    public fun clearForCondition() {
      _builder.clearForCondition()
    }
    /**
     * `.protocol.ForCondition forCondition = 1;`
     * @return Whether the forCondition field is set.
     */
    public fun hasForCondition(): kotlin.Boolean {
      return _builder.hasForCondition()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class StatementsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .protocol.Statement statements = 2;`
     */
     public val statements: com.google.protobuf.kotlin.DslList<protocol.Statements.Statement, StatementsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getStatementsList()
      )
    /**
     * `repeated .protocol.Statement statements = 2;`
     * @param value The statements to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addStatements")
    public fun com.google.protobuf.kotlin.DslList<protocol.Statements.Statement, StatementsProxy>.add(value: protocol.Statements.Statement) {
      _builder.addStatements(value)
    }
    /**
     * `repeated .protocol.Statement statements = 2;`
     * @param value The statements to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignStatements")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<protocol.Statements.Statement, StatementsProxy>.plusAssign(value: protocol.Statements.Statement) {
      add(value)
    }
    /**
     * `repeated .protocol.Statement statements = 2;`
     * @param values The statements to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllStatements")
    public fun com.google.protobuf.kotlin.DslList<protocol.Statements.Statement, StatementsProxy>.addAll(values: kotlin.collections.Iterable<protocol.Statements.Statement>) {
      _builder.addAllStatements(values)
    }
    /**
     * `repeated .protocol.Statement statements = 2;`
     * @param values The statements to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllStatements")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<protocol.Statements.Statement, StatementsProxy>.plusAssign(values: kotlin.collections.Iterable<protocol.Statements.Statement>) {
      addAll(values)
    }
    /**
     * `repeated .protocol.Statement statements = 2;`
     * @param index The index to set the value at.
     * @param value The statements to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setStatements")
    public operator fun com.google.protobuf.kotlin.DslList<protocol.Statements.Statement, StatementsProxy>.set(index: kotlin.Int, value: protocol.Statements.Statement) {
      _builder.setStatements(index, value)
    }
    /**
     * `repeated .protocol.Statement statements = 2;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearStatements")
    public fun com.google.protobuf.kotlin.DslList<protocol.Statements.Statement, StatementsProxy>.clear() {
      _builder.clearStatements()
    }


    /**
     * `.protocol.Position position = 3;`
     */
    public var position: protocol.PositionOuterClass.Position
      @JvmName("getPosition")
      get() = _builder.getPosition()
      @JvmName("setPosition")
      set(value) {
        _builder.setPosition(value)
      }
    /**
     * `.protocol.Position position = 3;`
     */
    public fun clearPosition() {
      _builder.clearPosition()
    }
    /**
     * `.protocol.Position position = 3;`
     * @return Whether the position field is set.
     */
    public fun hasPosition(): kotlin.Boolean {
      return _builder.hasPosition()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun protocol.Statements.ForDefinitionStatement.copy(block: `protocol`.ForDefinitionStatementKt.Dsl.() -> kotlin.Unit): protocol.Statements.ForDefinitionStatement =
  `protocol`.ForDefinitionStatementKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val protocol.Statements.ForDefinitionStatementOrBuilder.forConditionOrNull: protocol.Statements.ForCondition?
  get() = if (hasForCondition()) getForCondition() else null

public val protocol.Statements.ForDefinitionStatementOrBuilder.positionOrNull: protocol.PositionOuterClass.Position?
  get() = if (hasPosition()) getPosition() else null

