// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: statements.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package protocol;

@kotlin.jvm.JvmName("-initializeforEachCondition")
public inline fun forEachCondition(block: protocol.ForEachConditionKt.Dsl.() -> kotlin.Unit): protocol.Statements.ForEachCondition =
  protocol.ForEachConditionKt.Dsl._create(protocol.Statements.ForEachCondition.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `protocol.ForEachCondition`
 */
public object ForEachConditionKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: protocol.Statements.ForEachCondition.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: protocol.Statements.ForEachCondition.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): protocol.Statements.ForEachCondition = _builder.build()

    /**
     * `.protocol.ItemDefinition itemDefinition = 1;`
     */
    public var itemDefinition: protocol.Statements.ItemDefinition
      @JvmName("getItemDefinition")
      get() = _builder.getItemDefinition()
      @JvmName("setItemDefinition")
      set(value) {
        _builder.setItemDefinition(value)
      }
    /**
     * `.protocol.ItemDefinition itemDefinition = 1;`
     */
    public fun clearItemDefinition() {
      _builder.clearItemDefinition()
    }
    /**
     * `.protocol.ItemDefinition itemDefinition = 1;`
     * @return Whether the itemDefinition field is set.
     */
    public fun hasItemDefinition(): kotlin.Boolean {
      return _builder.hasItemDefinition()
    }

    /**
     * `.protocol.Expression expression = 2;`
     */
    public var expression: protocol.Expressions.Expression
      @JvmName("getExpression")
      get() = _builder.getExpression()
      @JvmName("setExpression")
      set(value) {
        _builder.setExpression(value)
      }
    /**
     * `.protocol.Expression expression = 2;`
     */
    public fun clearExpression() {
      _builder.clearExpression()
    }
    /**
     * `.protocol.Expression expression = 2;`
     * @return Whether the expression field is set.
     */
    public fun hasExpression(): kotlin.Boolean {
      return _builder.hasExpression()
    }

    /**
     * `optional .protocol.Position position = 3;`
     */
    public var position: protocol.PositionOuterClass.Position
      @JvmName("getPosition")
      get() = _builder.getPosition()
      @JvmName("setPosition")
      set(value) {
        _builder.setPosition(value)
      }
    /**
     * `optional .protocol.Position position = 3;`
     */
    public fun clearPosition() {
      _builder.clearPosition()
    }
    /**
     * `optional .protocol.Position position = 3;`
     * @return Whether the position field is set.
     */
    public fun hasPosition(): kotlin.Boolean {
      return _builder.hasPosition()
    }
    public val ForEachConditionKt.Dsl.positionOrNull: protocol.PositionOuterClass.Position?
      get() = _builder.positionOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun protocol.Statements.ForEachCondition.copy(block: `protocol`.ForEachConditionKt.Dsl.() -> kotlin.Unit): protocol.Statements.ForEachCondition =
  `protocol`.ForEachConditionKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val protocol.Statements.ForEachConditionOrBuilder.itemDefinitionOrNull: protocol.Statements.ItemDefinition?
  get() = if (hasItemDefinition()) getItemDefinition() else null

public val protocol.Statements.ForEachConditionOrBuilder.expressionOrNull: protocol.Expressions.Expression?
  get() = if (hasExpression()) getExpression() else null

public val protocol.Statements.ForEachConditionOrBuilder.positionOrNull: protocol.PositionOuterClass.Position?
  get() = if (hasPosition()) getPosition() else null

