// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: statements.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package protocol;

@kotlin.jvm.JvmName("-initializefunctionDefinitionStatement")
public inline fun functionDefinitionStatement(block: protocol.FunctionDefinitionStatementKt.Dsl.() -> kotlin.Unit): protocol.Statements.FunctionDefinitionStatement =
  protocol.FunctionDefinitionStatementKt.Dsl._create(protocol.Statements.FunctionDefinitionStatement.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `protocol.FunctionDefinitionStatement`
 */
public object FunctionDefinitionStatementKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: protocol.Statements.FunctionDefinitionStatement.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: protocol.Statements.FunctionDefinitionStatement.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): protocol.Statements.FunctionDefinitionStatement = _builder.build()

    /**
     * `string name = 1;`
     */
    public var name: kotlin.String
      @JvmName("getName")
      get() = _builder.getName()
      @JvmName("setName")
      set(value) {
        _builder.setName(value)
      }
    /**
     * `string name = 1;`
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ParametersProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .protocol.Parameter parameters = 2;`
     */
     public val parameters: com.google.protobuf.kotlin.DslList<protocol.Statements.Parameter, ParametersProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getParametersList()
      )
    /**
     * `repeated .protocol.Parameter parameters = 2;`
     * @param value The parameters to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addParameters")
    public fun com.google.protobuf.kotlin.DslList<protocol.Statements.Parameter, ParametersProxy>.add(value: protocol.Statements.Parameter) {
      _builder.addParameters(value)
    }
    /**
     * `repeated .protocol.Parameter parameters = 2;`
     * @param value The parameters to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignParameters")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<protocol.Statements.Parameter, ParametersProxy>.plusAssign(value: protocol.Statements.Parameter) {
      add(value)
    }
    /**
     * `repeated .protocol.Parameter parameters = 2;`
     * @param values The parameters to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllParameters")
    public fun com.google.protobuf.kotlin.DslList<protocol.Statements.Parameter, ParametersProxy>.addAll(values: kotlin.collections.Iterable<protocol.Statements.Parameter>) {
      _builder.addAllParameters(values)
    }
    /**
     * `repeated .protocol.Parameter parameters = 2;`
     * @param values The parameters to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllParameters")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<protocol.Statements.Parameter, ParametersProxy>.plusAssign(values: kotlin.collections.Iterable<protocol.Statements.Parameter>) {
      addAll(values)
    }
    /**
     * `repeated .protocol.Parameter parameters = 2;`
     * @param index The index to set the value at.
     * @param value The parameters to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setParameters")
    public operator fun com.google.protobuf.kotlin.DslList<protocol.Statements.Parameter, ParametersProxy>.set(index: kotlin.Int, value: protocol.Statements.Parameter) {
      _builder.setParameters(index, value)
    }
    /**
     * `repeated .protocol.Parameter parameters = 2;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearParameters")
    public fun com.google.protobuf.kotlin.DslList<protocol.Statements.Parameter, ParametersProxy>.clear() {
      _builder.clearParameters()
    }


    /**
     * `.protocol.VariableValueType returnType = 3;`
     */
    public var returnType: protocol.Statements.VariableValueType
      @JvmName("getReturnType")
      get() = _builder.getReturnType()
      @JvmName("setReturnType")
      set(value) {
        _builder.setReturnType(value)
      }
    /**
     * `.protocol.VariableValueType returnType = 3;`
     */
    public fun clearReturnType() {
      _builder.clearReturnType()
    }
    /**
     * `.protocol.VariableValueType returnType = 3;`
     * @return Whether the returnType field is set.
     */
    public fun hasReturnType(): kotlin.Boolean {
      return _builder.hasReturnType()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class StatementsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .protocol.Statement statements = 4;`
     */
     public val statements: com.google.protobuf.kotlin.DslList<protocol.Statements.Statement, StatementsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getStatementsList()
      )
    /**
     * `repeated .protocol.Statement statements = 4;`
     * @param value The statements to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addStatements")
    public fun com.google.protobuf.kotlin.DslList<protocol.Statements.Statement, StatementsProxy>.add(value: protocol.Statements.Statement) {
      _builder.addStatements(value)
    }
    /**
     * `repeated .protocol.Statement statements = 4;`
     * @param value The statements to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignStatements")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<protocol.Statements.Statement, StatementsProxy>.plusAssign(value: protocol.Statements.Statement) {
      add(value)
    }
    /**
     * `repeated .protocol.Statement statements = 4;`
     * @param values The statements to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllStatements")
    public fun com.google.protobuf.kotlin.DslList<protocol.Statements.Statement, StatementsProxy>.addAll(values: kotlin.collections.Iterable<protocol.Statements.Statement>) {
      _builder.addAllStatements(values)
    }
    /**
     * `repeated .protocol.Statement statements = 4;`
     * @param values The statements to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllStatements")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<protocol.Statements.Statement, StatementsProxy>.plusAssign(values: kotlin.collections.Iterable<protocol.Statements.Statement>) {
      addAll(values)
    }
    /**
     * `repeated .protocol.Statement statements = 4;`
     * @param index The index to set the value at.
     * @param value The statements to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setStatements")
    public operator fun com.google.protobuf.kotlin.DslList<protocol.Statements.Statement, StatementsProxy>.set(index: kotlin.Int, value: protocol.Statements.Statement) {
      _builder.setStatements(index, value)
    }
    /**
     * `repeated .protocol.Statement statements = 4;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearStatements")
    public fun com.google.protobuf.kotlin.DslList<protocol.Statements.Statement, StatementsProxy>.clear() {
      _builder.clearStatements()
    }


    /**
     * `optional .protocol.Position position = 5;`
     */
    public var position: protocol.PositionOuterClass.Position
      @JvmName("getPosition")
      get() = _builder.getPosition()
      @JvmName("setPosition")
      set(value) {
        _builder.setPosition(value)
      }
    /**
     * `optional .protocol.Position position = 5;`
     */
    public fun clearPosition() {
      _builder.clearPosition()
    }
    /**
     * `optional .protocol.Position position = 5;`
     * @return Whether the position field is set.
     */
    public fun hasPosition(): kotlin.Boolean {
      return _builder.hasPosition()
    }
    public val FunctionDefinitionStatementKt.Dsl.positionOrNull: protocol.PositionOuterClass.Position?
      get() = _builder.positionOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun protocol.Statements.FunctionDefinitionStatement.copy(block: `protocol`.FunctionDefinitionStatementKt.Dsl.() -> kotlin.Unit): protocol.Statements.FunctionDefinitionStatement =
  `protocol`.FunctionDefinitionStatementKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val protocol.Statements.FunctionDefinitionStatementOrBuilder.returnTypeOrNull: protocol.Statements.VariableValueType?
  get() = if (hasReturnType()) getReturnType() else null

public val protocol.Statements.FunctionDefinitionStatementOrBuilder.positionOrNull: protocol.PositionOuterClass.Position?
  get() = if (hasPosition()) getPosition() else null

