// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: response.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package protocol;

@kotlin.jvm.JvmName("-initializegenerateCodeResponse")
public inline fun generateCodeResponse(block: protocol.GenerateCodeResponseKt.Dsl.() -> kotlin.Unit): protocol.Response.GenerateCodeResponse =
  protocol.GenerateCodeResponseKt.Dsl._create(protocol.Response.GenerateCodeResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `protocol.GenerateCodeResponse`
 */
public object GenerateCodeResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: protocol.Response.GenerateCodeResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: protocol.Response.GenerateCodeResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): protocol.Response.GenerateCodeResponse = _builder.build()

    /**
     * `bool success = 1;`
     */
    public var success: kotlin.Boolean
      @JvmName("getSuccess")
      get() = _builder.getSuccess()
      @JvmName("setSuccess")
      set(value) {
        _builder.setSuccess(value)
      }
    /**
     * `bool success = 1;`
     */
    public fun clearSuccess() {
      _builder.clearSuccess()
    }

    /**
     * `string code = 2;`
     */
    public var code: kotlin.String
      @JvmName("getCode")
      get() = _builder.getCode()
      @JvmName("setCode")
      set(value) {
        _builder.setCode(value)
      }
    /**
     * `string code = 2;`
     */
    public fun clearCode() {
      _builder.clearCode()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ErrorsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .protocol.LanguageError errors = 3;`
     */
     public val errors: com.google.protobuf.kotlin.DslList<protocol.Response.LanguageError, ErrorsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getErrorsList()
      )
    /**
     * `repeated .protocol.LanguageError errors = 3;`
     * @param value The errors to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addErrors")
    public fun com.google.protobuf.kotlin.DslList<protocol.Response.LanguageError, ErrorsProxy>.add(value: protocol.Response.LanguageError) {
      _builder.addErrors(value)
    }
    /**
     * `repeated .protocol.LanguageError errors = 3;`
     * @param value The errors to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignErrors")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<protocol.Response.LanguageError, ErrorsProxy>.plusAssign(value: protocol.Response.LanguageError) {
      add(value)
    }
    /**
     * `repeated .protocol.LanguageError errors = 3;`
     * @param values The errors to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllErrors")
    public fun com.google.protobuf.kotlin.DslList<protocol.Response.LanguageError, ErrorsProxy>.addAll(values: kotlin.collections.Iterable<protocol.Response.LanguageError>) {
      _builder.addAllErrors(values)
    }
    /**
     * `repeated .protocol.LanguageError errors = 3;`
     * @param values The errors to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllErrors")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<protocol.Response.LanguageError, ErrorsProxy>.plusAssign(values: kotlin.collections.Iterable<protocol.Response.LanguageError>) {
      addAll(values)
    }
    /**
     * `repeated .protocol.LanguageError errors = 3;`
     * @param index The index to set the value at.
     * @param value The errors to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setErrors")
    public operator fun com.google.protobuf.kotlin.DslList<protocol.Response.LanguageError, ErrorsProxy>.set(index: kotlin.Int, value: protocol.Response.LanguageError) {
      _builder.setErrors(index, value)
    }
    /**
     * `repeated .protocol.LanguageError errors = 3;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearErrors")
    public fun com.google.protobuf.kotlin.DslList<protocol.Response.LanguageError, ErrorsProxy>.clear() {
      _builder.clearErrors()
    }

  }
}
@kotlin.jvm.JvmSynthetic
public inline fun protocol.Response.GenerateCodeResponse.copy(block: `protocol`.GenerateCodeResponseKt.Dsl.() -> kotlin.Unit): protocol.Response.GenerateCodeResponse =
  `protocol`.GenerateCodeResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

