// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: statements.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package protocol;

@kotlin.jvm.JvmName("-initializeitemDefinition")
public inline fun itemDefinition(block: protocol.ItemDefinitionKt.Dsl.() -> kotlin.Unit): protocol.Statements.ItemDefinition =
  protocol.ItemDefinitionKt.Dsl._create(protocol.Statements.ItemDefinition.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `protocol.ItemDefinition`
 */
public object ItemDefinitionKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: protocol.Statements.ItemDefinition.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: protocol.Statements.ItemDefinition.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): protocol.Statements.ItemDefinition = _builder.build()

    /**
     * `.protocol.VariableType varType = 1;`
     */
    public var varType: protocol.Statements.VariableType
      @JvmName("getVarType")
      get() = _builder.getVarType()
      @JvmName("setVarType")
      set(value) {
        _builder.setVarType(value)
      }
    public var varTypeValue: kotlin.Int
      @JvmName("getVarTypeValue")
      get() = _builder.getVarTypeValue()
      @JvmName("setVarTypeValue")
      set(value) {
        _builder.setVarTypeValue(value)
      }
    /**
     * `.protocol.VariableType varType = 1;`
     */
    public fun clearVarType() {
      _builder.clearVarType()
    }

    /**
     * `string name = 2;`
     */
    public var name: kotlin.String
      @JvmName("getName")
      get() = _builder.getName()
      @JvmName("setName")
      set(value) {
        _builder.setName(value)
      }
    /**
     * `string name = 2;`
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * `.protocol.VariableValueType valueType = 3;`
     */
    public var valueType: protocol.Statements.VariableValueType
      @JvmName("getValueType")
      get() = _builder.getValueType()
      @JvmName("setValueType")
      set(value) {
        _builder.setValueType(value)
      }
    /**
     * `.protocol.VariableValueType valueType = 3;`
     */
    public fun clearValueType() {
      _builder.clearValueType()
    }
    /**
     * `.protocol.VariableValueType valueType = 3;`
     * @return Whether the valueType field is set.
     */
    public fun hasValueType(): kotlin.Boolean {
      return _builder.hasValueType()
    }

    /**
     * `optional .protocol.Position position = 4;`
     */
    public var position: protocol.PositionOuterClass.Position
      @JvmName("getPosition")
      get() = _builder.getPosition()
      @JvmName("setPosition")
      set(value) {
        _builder.setPosition(value)
      }
    /**
     * `optional .protocol.Position position = 4;`
     */
    public fun clearPosition() {
      _builder.clearPosition()
    }
    /**
     * `optional .protocol.Position position = 4;`
     * @return Whether the position field is set.
     */
    public fun hasPosition(): kotlin.Boolean {
      return _builder.hasPosition()
    }
    public val ItemDefinitionKt.Dsl.positionOrNull: protocol.PositionOuterClass.Position?
      get() = _builder.positionOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun protocol.Statements.ItemDefinition.copy(block: `protocol`.ItemDefinitionKt.Dsl.() -> kotlin.Unit): protocol.Statements.ItemDefinition =
  `protocol`.ItemDefinitionKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val protocol.Statements.ItemDefinitionOrBuilder.valueTypeOrNull: protocol.Statements.VariableValueType?
  get() = if (hasValueType()) getValueType() else null

public val protocol.Statements.ItemDefinitionOrBuilder.positionOrNull: protocol.PositionOuterClass.Position?
  get() = if (hasPosition()) getPosition() else null

