// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: expressions.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package protocol;

@kotlin.jvm.JvmName("-initializeobjectMethodCallExpression")
public inline fun objectMethodCallExpression(block: protocol.ObjectMethodCallExpressionKt.Dsl.() -> kotlin.Unit): protocol.Expressions.ObjectMethodCallExpression =
  protocol.ObjectMethodCallExpressionKt.Dsl._create(protocol.Expressions.ObjectMethodCallExpression.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `protocol.ObjectMethodCallExpression`
 */
public object ObjectMethodCallExpressionKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: protocol.Expressions.ObjectMethodCallExpression.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: protocol.Expressions.ObjectMethodCallExpression.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): protocol.Expressions.ObjectMethodCallExpression = _builder.build()

    /**
     * `string objectName = 1;`
     */
    public var objectName: kotlin.String
      @JvmName("getObjectName")
      get() = _builder.getObjectName()
      @JvmName("setObjectName")
      set(value) {
        _builder.setObjectName(value)
      }
    /**
     * `string objectName = 1;`
     */
    public fun clearObjectName() {
      _builder.clearObjectName()
    }

    /**
     * `string methodName = 2;`
     */
    public var methodName: kotlin.String
      @JvmName("getMethodName")
      get() = _builder.getMethodName()
      @JvmName("setMethodName")
      set(value) {
        _builder.setMethodName(value)
      }
    /**
     * `string methodName = 2;`
     */
    public fun clearMethodName() {
      _builder.clearMethodName()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ParametersProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .protocol.Expression parameters = 3;`
     */
     public val parameters: com.google.protobuf.kotlin.DslList<protocol.Expressions.Expression, ParametersProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getParametersList()
      )
    /**
     * `repeated .protocol.Expression parameters = 3;`
     * @param value The parameters to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addParameters")
    public fun com.google.protobuf.kotlin.DslList<protocol.Expressions.Expression, ParametersProxy>.add(value: protocol.Expressions.Expression) {
      _builder.addParameters(value)
    }
    /**
     * `repeated .protocol.Expression parameters = 3;`
     * @param value The parameters to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignParameters")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<protocol.Expressions.Expression, ParametersProxy>.plusAssign(value: protocol.Expressions.Expression) {
      add(value)
    }
    /**
     * `repeated .protocol.Expression parameters = 3;`
     * @param values The parameters to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllParameters")
    public fun com.google.protobuf.kotlin.DslList<protocol.Expressions.Expression, ParametersProxy>.addAll(values: kotlin.collections.Iterable<protocol.Expressions.Expression>) {
      _builder.addAllParameters(values)
    }
    /**
     * `repeated .protocol.Expression parameters = 3;`
     * @param values The parameters to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllParameters")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<protocol.Expressions.Expression, ParametersProxy>.plusAssign(values: kotlin.collections.Iterable<protocol.Expressions.Expression>) {
      addAll(values)
    }
    /**
     * `repeated .protocol.Expression parameters = 3;`
     * @param index The index to set the value at.
     * @param value The parameters to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setParameters")
    public operator fun com.google.protobuf.kotlin.DslList<protocol.Expressions.Expression, ParametersProxy>.set(index: kotlin.Int, value: protocol.Expressions.Expression) {
      _builder.setParameters(index, value)
    }
    /**
     * `repeated .protocol.Expression parameters = 3;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearParameters")
    public fun com.google.protobuf.kotlin.DslList<protocol.Expressions.Expression, ParametersProxy>.clear() {
      _builder.clearParameters()
    }


    /**
     * `.protocol.Position position = 4;`
     */
    public var position: protocol.PositionOuterClass.Position
      @JvmName("getPosition")
      get() = _builder.getPosition()
      @JvmName("setPosition")
      set(value) {
        _builder.setPosition(value)
      }
    /**
     * `.protocol.Position position = 4;`
     */
    public fun clearPosition() {
      _builder.clearPosition()
    }
    /**
     * `.protocol.Position position = 4;`
     * @return Whether the position field is set.
     */
    public fun hasPosition(): kotlin.Boolean {
      return _builder.hasPosition()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun protocol.Expressions.ObjectMethodCallExpression.copy(block: `protocol`.ObjectMethodCallExpressionKt.Dsl.() -> kotlin.Unit): protocol.Expressions.ObjectMethodCallExpression =
  `protocol`.ObjectMethodCallExpressionKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val protocol.Expressions.ObjectMethodCallExpressionOrBuilder.positionOrNull: protocol.PositionOuterClass.Position?
  get() = if (hasPosition()) getPosition() else null

