// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: statements.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package protocol;

@kotlin.jvm.JvmName("-initializeparameter")
public inline fun parameter(block: protocol.ParameterKt.Dsl.() -> kotlin.Unit): protocol.Statements.Parameter =
  protocol.ParameterKt.Dsl._create(protocol.Statements.Parameter.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `protocol.Parameter`
 */
public object ParameterKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: protocol.Statements.Parameter.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: protocol.Statements.Parameter.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): protocol.Statements.Parameter = _builder.build()

    /**
     * `string name = 1;`
     */
    public var name: kotlin.String
      @JvmName("getName")
      get() = _builder.getName()
      @JvmName("setName")
      set(value) {
        _builder.setName(value)
      }
    /**
     * `string name = 1;`
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * `.protocol.ParameterType type = 2;`
     */
    public var type: protocol.Statements.ParameterType
      @JvmName("getType")
      get() = _builder.getType()
      @JvmName("setType")
      set(value) {
        _builder.setType(value)
      }
    public var typeValue: kotlin.Int
      @JvmName("getTypeValue")
      get() = _builder.getTypeValue()
      @JvmName("setTypeValue")
      set(value) {
        _builder.setTypeValue(value)
      }
    /**
     * `.protocol.ParameterType type = 2;`
     */
    public fun clearType() {
      _builder.clearType()
    }

    /**
     * `.protocol.VariableValueType valueType = 3;`
     */
    public var valueType: protocol.Statements.VariableValueType
      @JvmName("getValueType")
      get() = _builder.getValueType()
      @JvmName("setValueType")
      set(value) {
        _builder.setValueType(value)
      }
    /**
     * `.protocol.VariableValueType valueType = 3;`
     */
    public fun clearValueType() {
      _builder.clearValueType()
    }
    /**
     * `.protocol.VariableValueType valueType = 3;`
     * @return Whether the valueType field is set.
     */
    public fun hasValueType(): kotlin.Boolean {
      return _builder.hasValueType()
    }

    /**
     * `optional .protocol.Position position = 4;`
     */
    public var position: protocol.PositionOuterClass.Position
      @JvmName("getPosition")
      get() = _builder.getPosition()
      @JvmName("setPosition")
      set(value) {
        _builder.setPosition(value)
      }
    /**
     * `optional .protocol.Position position = 4;`
     */
    public fun clearPosition() {
      _builder.clearPosition()
    }
    /**
     * `optional .protocol.Position position = 4;`
     * @return Whether the position field is set.
     */
    public fun hasPosition(): kotlin.Boolean {
      return _builder.hasPosition()
    }
    public val ParameterKt.Dsl.positionOrNull: protocol.PositionOuterClass.Position?
      get() = _builder.positionOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun protocol.Statements.Parameter.copy(block: `protocol`.ParameterKt.Dsl.() -> kotlin.Unit): protocol.Statements.Parameter =
  `protocol`.ParameterKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val protocol.Statements.ParameterOrBuilder.valueTypeOrNull: protocol.Statements.VariableValueType?
  get() = if (hasValueType()) getValueType() else null

public val protocol.Statements.ParameterOrBuilder.positionOrNull: protocol.PositionOuterClass.Position?
  get() = if (hasPosition()) getPosition() else null

