// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: position.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package protocol;

@kotlin.jvm.JvmName("-initializepoint")
public inline fun point(block: protocol.PointKt.Dsl.() -> kotlin.Unit): protocol.PositionOuterClass.Point =
  protocol.PointKt.Dsl._create(protocol.PositionOuterClass.Point.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `protocol.Point`
 */
public object PointKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: protocol.PositionOuterClass.Point.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: protocol.PositionOuterClass.Point.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): protocol.PositionOuterClass.Point = _builder.build()

    /**
     * `int32 line = 1;`
     */
    public var line: kotlin.Int
      @JvmName("getLine")
      get() = _builder.getLine()
      @JvmName("setLine")
      set(value) {
        _builder.setLine(value)
      }
    /**
     * `int32 line = 1;`
     */
    public fun clearLine() {
      _builder.clearLine()
    }

    /**
     * `int32 column = 2;`
     */
    public var column: kotlin.Int
      @JvmName("getColumn")
      get() = _builder.getColumn()
      @JvmName("setColumn")
      set(value) {
        _builder.setColumn(value)
      }
    /**
     * `int32 column = 2;`
     */
    public fun clearColumn() {
      _builder.clearColumn()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun protocol.PositionOuterClass.Point.copy(block: `protocol`.PointKt.Dsl.() -> kotlin.Unit): protocol.PositionOuterClass.Point =
  `protocol`.PointKt.Dsl._create(this.toBuilder()).apply { block() }._build()

