// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: base.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package protocol;

@kotlin.jvm.JvmName("-initializeprogramFile")
public inline fun programFile(block: protocol.ProgramFileKt.Dsl.() -> kotlin.Unit): protocol.Base.ProgramFile =
  protocol.ProgramFileKt.Dsl._create(protocol.Base.ProgramFile.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `protocol.ProgramFile`
 */
public object ProgramFileKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: protocol.Base.ProgramFile.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: protocol.Base.ProgramFile.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): protocol.Base.ProgramFile = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class LinesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * Lists in Kotlin are represented as repeated fields in proto3
     * ```
     *
     * `repeated .protocol.Statement lines = 1;`
     */
     public val lines: com.google.protobuf.kotlin.DslList<protocol.Statements.Statement, LinesProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getLinesList()
      )
    /**
     * ```
     * Lists in Kotlin are represented as repeated fields in proto3
     * ```
     *
     * `repeated .protocol.Statement lines = 1;`
     * @param value The lines to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addLines")
    public fun com.google.protobuf.kotlin.DslList<protocol.Statements.Statement, LinesProxy>.add(value: protocol.Statements.Statement) {
      _builder.addLines(value)
    }
    /**
     * ```
     * Lists in Kotlin are represented as repeated fields in proto3
     * ```
     *
     * `repeated .protocol.Statement lines = 1;`
     * @param value The lines to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignLines")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<protocol.Statements.Statement, LinesProxy>.plusAssign(value: protocol.Statements.Statement) {
      add(value)
    }
    /**
     * ```
     * Lists in Kotlin are represented as repeated fields in proto3
     * ```
     *
     * `repeated .protocol.Statement lines = 1;`
     * @param values The lines to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllLines")
    public fun com.google.protobuf.kotlin.DslList<protocol.Statements.Statement, LinesProxy>.addAll(values: kotlin.collections.Iterable<protocol.Statements.Statement>) {
      _builder.addAllLines(values)
    }
    /**
     * ```
     * Lists in Kotlin are represented as repeated fields in proto3
     * ```
     *
     * `repeated .protocol.Statement lines = 1;`
     * @param values The lines to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllLines")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<protocol.Statements.Statement, LinesProxy>.plusAssign(values: kotlin.collections.Iterable<protocol.Statements.Statement>) {
      addAll(values)
    }
    /**
     * ```
     * Lists in Kotlin are represented as repeated fields in proto3
     * ```
     *
     * `repeated .protocol.Statement lines = 1;`
     * @param index The index to set the value at.
     * @param value The lines to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setLines")
    public operator fun com.google.protobuf.kotlin.DslList<protocol.Statements.Statement, LinesProxy>.set(index: kotlin.Int, value: protocol.Statements.Statement) {
      _builder.setLines(index, value)
    }
    /**
     * ```
     * Lists in Kotlin are represented as repeated fields in proto3
     * ```
     *
     * `repeated .protocol.Statement lines = 1;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearLines")
    public fun com.google.protobuf.kotlin.DslList<protocol.Statements.Statement, LinesProxy>.clear() {
      _builder.clearLines()
    }


    /**
     * `.protocol.Position position = 2;`
     */
    public var position: protocol.PositionOuterClass.Position
      @JvmName("getPosition")
      get() = _builder.getPosition()
      @JvmName("setPosition")
      set(value) {
        _builder.setPosition(value)
      }
    /**
     * `.protocol.Position position = 2;`
     */
    public fun clearPosition() {
      _builder.clearPosition()
    }
    /**
     * `.protocol.Position position = 2;`
     * @return Whether the position field is set.
     */
    public fun hasPosition(): kotlin.Boolean {
      return _builder.hasPosition()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun protocol.Base.ProgramFile.copy(block: `protocol`.ProgramFileKt.Dsl.() -> kotlin.Unit): protocol.Base.ProgramFile =
  `protocol`.ProgramFileKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val protocol.Base.ProgramFileOrBuilder.positionOrNull: protocol.PositionOuterClass.Position?
  get() = if (hasPosition()) getPosition() else null

