// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: statements.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package protocol;

@kotlin.jvm.JvmName("-initializevarDeclarationForStatement")
public inline fun varDeclarationForStatement(block: protocol.VarDeclarationForStatementKt.Dsl.() -> kotlin.Unit): protocol.Statements.VarDeclarationForStatement =
  protocol.VarDeclarationForStatementKt.Dsl._create(protocol.Statements.VarDeclarationForStatement.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `protocol.VarDeclarationForStatement`
 */
public object VarDeclarationForStatementKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: protocol.Statements.VarDeclarationForStatement.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: protocol.Statements.VarDeclarationForStatement.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): protocol.Statements.VarDeclarationForStatement = _builder.build()

    /**
     * `.protocol.VariableType varType = 1;`
     */
    public var varType: protocol.Statements.VariableType
      @JvmName("getVarType")
      get() = _builder.getVarType()
      @JvmName("setVarType")
      set(value) {
        _builder.setVarType(value)
      }
    public var varTypeValue: kotlin.Int
      @JvmName("getVarTypeValue")
      get() = _builder.getVarTypeValue()
      @JvmName("setVarTypeValue")
      set(value) {
        _builder.setVarTypeValue(value)
      }
    /**
     * `.protocol.VariableType varType = 1;`
     */
    public fun clearVarType() {
      _builder.clearVarType()
    }

    /**
     * `string name = 2;`
     */
    public var name: kotlin.String
      @JvmName("getName")
      get() = _builder.getName()
      @JvmName("setName")
      set(value) {
        _builder.setName(value)
      }
    /**
     * `string name = 2;`
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * `.protocol.VariableValueType valueType = 3;`
     */
    public var valueType: protocol.Statements.VariableValueType
      @JvmName("getValueType")
      get() = _builder.getValueType()
      @JvmName("setValueType")
      set(value) {
        _builder.setValueType(value)
      }
    /**
     * `.protocol.VariableValueType valueType = 3;`
     */
    public fun clearValueType() {
      _builder.clearValueType()
    }
    /**
     * `.protocol.VariableValueType valueType = 3;`
     * @return Whether the valueType field is set.
     */
    public fun hasValueType(): kotlin.Boolean {
      return _builder.hasValueType()
    }

    /**
     * `.protocol.Expression value = 4;`
     */
    public var value: protocol.Expressions.Expression
      @JvmName("getValue")
      get() = _builder.getValue()
      @JvmName("setValue")
      set(value) {
        _builder.setValue(value)
      }
    /**
     * `.protocol.Expression value = 4;`
     */
    public fun clearValue() {
      _builder.clearValue()
    }
    /**
     * `.protocol.Expression value = 4;`
     * @return Whether the value field is set.
     */
    public fun hasValue(): kotlin.Boolean {
      return _builder.hasValue()
    }

    /**
     * `optional .protocol.Position position = 5;`
     */
    public var position: protocol.PositionOuterClass.Position
      @JvmName("getPosition")
      get() = _builder.getPosition()
      @JvmName("setPosition")
      set(value) {
        _builder.setPosition(value)
      }
    /**
     * `optional .protocol.Position position = 5;`
     */
    public fun clearPosition() {
      _builder.clearPosition()
    }
    /**
     * `optional .protocol.Position position = 5;`
     * @return Whether the position field is set.
     */
    public fun hasPosition(): kotlin.Boolean {
      return _builder.hasPosition()
    }
    public val VarDeclarationForStatementKt.Dsl.positionOrNull: protocol.PositionOuterClass.Position?
      get() = _builder.positionOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun protocol.Statements.VarDeclarationForStatement.copy(block: `protocol`.VarDeclarationForStatementKt.Dsl.() -> kotlin.Unit): protocol.Statements.VarDeclarationForStatement =
  `protocol`.VarDeclarationForStatementKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val protocol.Statements.VarDeclarationForStatementOrBuilder.valueTypeOrNull: protocol.Statements.VariableValueType?
  get() = if (hasValueType()) getValueType() else null

public val protocol.Statements.VarDeclarationForStatementOrBuilder.valueOrNull: protocol.Expressions.Expression?
  get() = if (hasValue()) getValue() else null

public val protocol.Statements.VarDeclarationForStatementOrBuilder.positionOrNull: protocol.PositionOuterClass.Position?
  get() = if (hasPosition()) getPosition() else null

