// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: statements.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package protocol;

@kotlin.jvm.JvmName("-initializevariableValueType")
public inline fun variableValueType(block: protocol.VariableValueTypeKt.Dsl.() -> kotlin.Unit): protocol.Statements.VariableValueType =
  protocol.VariableValueTypeKt.Dsl._create(protocol.Statements.VariableValueType.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `protocol.VariableValueType`
 */
public object VariableValueTypeKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: protocol.Statements.VariableValueType.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: protocol.Statements.VariableValueType.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): protocol.Statements.VariableValueType = _builder.build()

    /**
     * `string name = 1;`
     */
    public var name: kotlin.String
      @JvmName("getName")
      get() = _builder.getName()
      @JvmName("setName")
      set(value) {
        _builder.setName(value)
      }
    /**
     * `string name = 1;`
     */
    public fun clearName() {
      _builder.clearName()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun protocol.Statements.VariableValueType.copy(block: `protocol`.VariableValueTypeKt.Dsl.() -> kotlin.Unit): protocol.Statements.VariableValueType =
  `protocol`.VariableValueTypeKt.Dsl._create(this.toBuilder()).apply { block() }._build()

