POST  http://localhost:8080/generate-ast
Accept: text/plain

{
"code": "fun main(){ \n val pi = 3.14 \n }"
}

###

POST http://localhost:8080/generate-code
Accept: text/plain

{
"ast": {
    "lines": [{
      "functionDefinitionStatement": {
        "name": "main",
        "returnType": {
          "name": "void"
        },
        "statements": [{
          "varDeclarationStatement": {
            "varType": "IMMUTABLE",
            "name": "pi",
            "value": {
              "decLit": {
                "value": "3.14",
                "position": {
                  "start": {
                    "line": 2,
                    "column": 11
                  },
                  "end": {
                    "line": 2,
                    "column": 15
                  }
                }
              }
            },
            "position": {
              "start": {
                "line": 2,
                "column": 2
              },
              "end": {
                "line": 2,
                "column": 15
              }
            }
          }
        }],
        "position": {
          "start": {
            "line": 1,
            "column": 1
          },
          "end": {
            "line": 3,
            "column": 3
          }
        }
      }
    }],
    "position": {
      "start": {
        "line": 1,
        "column": 1
      },
      "end": {
        "line": 3,
        "column": 8
      }
    }
  }
}