POST  http://localhost:8080/ast
Accept: text/plain

pi = 3.14
###

POST http://localhost:8080/transpile
Accept: application/json

{
"ast": {"type":"ProgramFile", "lines":[{"type":"AssignmentStatement","name":"pi","value":{"type":"DecLit","value":"3.14","position":{"start":{"line":1,"column":6},"end":{"line":1,"column":10}}},"position":{"start":{"line":1,"column":1},"end":{"line":1,"column":10}}}],"position":{"start":{"line":1,"column":1},"end":{"line":1,"column":15}}}
}