// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: position.proto

// Protobuf Java Version: 3.25.3
package protocol;

public final class PositionOuterClass {
  private PositionOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PositionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.Position)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.protocol.Point start = 1;</code>
     * @return Whether the start field is set.
     */
    boolean hasStart();
    /**
     * <code>.protocol.Point start = 1;</code>
     * @return The start.
     */
    protocol.PositionOuterClass.Point getStart();
    /**
     * <code>.protocol.Point start = 1;</code>
     */
    protocol.PositionOuterClass.PointOrBuilder getStartOrBuilder();

    /**
     * <code>.protocol.Point end = 2;</code>
     * @return Whether the end field is set.
     */
    boolean hasEnd();
    /**
     * <code>.protocol.Point end = 2;</code>
     * @return The end.
     */
    protocol.PositionOuterClass.Point getEnd();
    /**
     * <code>.protocol.Point end = 2;</code>
     */
    protocol.PositionOuterClass.PointOrBuilder getEndOrBuilder();
  }
  /**
   * Protobuf type {@code protocol.Position}
   */
  public static final class Position extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol.Position)
      PositionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Position.newBuilder() to construct.
    private Position(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Position() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Position();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.PositionOuterClass.internal_static_protocol_Position_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.PositionOuterClass.internal_static_protocol_Position_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.PositionOuterClass.Position.class, protocol.PositionOuterClass.Position.Builder.class);
    }

    private int bitField0_;
    public static final int START_FIELD_NUMBER = 1;
    private protocol.PositionOuterClass.Point start_;
    /**
     * <code>.protocol.Point start = 1;</code>
     * @return Whether the start field is set.
     */
    @java.lang.Override
    public boolean hasStart() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.protocol.Point start = 1;</code>
     * @return The start.
     */
    @java.lang.Override
    public protocol.PositionOuterClass.Point getStart() {
      return start_ == null ? protocol.PositionOuterClass.Point.getDefaultInstance() : start_;
    }
    /**
     * <code>.protocol.Point start = 1;</code>
     */
    @java.lang.Override
    public protocol.PositionOuterClass.PointOrBuilder getStartOrBuilder() {
      return start_ == null ? protocol.PositionOuterClass.Point.getDefaultInstance() : start_;
    }

    public static final int END_FIELD_NUMBER = 2;
    private protocol.PositionOuterClass.Point end_;
    /**
     * <code>.protocol.Point end = 2;</code>
     * @return Whether the end field is set.
     */
    @java.lang.Override
    public boolean hasEnd() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.protocol.Point end = 2;</code>
     * @return The end.
     */
    @java.lang.Override
    public protocol.PositionOuterClass.Point getEnd() {
      return end_ == null ? protocol.PositionOuterClass.Point.getDefaultInstance() : end_;
    }
    /**
     * <code>.protocol.Point end = 2;</code>
     */
    @java.lang.Override
    public protocol.PositionOuterClass.PointOrBuilder getEndOrBuilder() {
      return end_ == null ? protocol.PositionOuterClass.Point.getDefaultInstance() : end_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getStart());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(2, getEnd());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getStart());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getEnd());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protocol.PositionOuterClass.Position)) {
        return super.equals(obj);
      }
      protocol.PositionOuterClass.Position other = (protocol.PositionOuterClass.Position) obj;

      if (hasStart() != other.hasStart()) return false;
      if (hasStart()) {
        if (!getStart()
            .equals(other.getStart())) return false;
      }
      if (hasEnd() != other.hasEnd()) return false;
      if (hasEnd()) {
        if (!getEnd()
            .equals(other.getEnd())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasStart()) {
        hash = (37 * hash) + START_FIELD_NUMBER;
        hash = (53 * hash) + getStart().hashCode();
      }
      if (hasEnd()) {
        hash = (37 * hash) + END_FIELD_NUMBER;
        hash = (53 * hash) + getEnd().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protocol.PositionOuterClass.Position parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.PositionOuterClass.Position parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.PositionOuterClass.Position parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.PositionOuterClass.Position parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.PositionOuterClass.Position parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.PositionOuterClass.Position parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.PositionOuterClass.Position parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.PositionOuterClass.Position parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static protocol.PositionOuterClass.Position parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static protocol.PositionOuterClass.Position parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.PositionOuterClass.Position parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.PositionOuterClass.Position parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocol.PositionOuterClass.Position prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.Position}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.Position)
        protocol.PositionOuterClass.PositionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.PositionOuterClass.internal_static_protocol_Position_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.PositionOuterClass.internal_static_protocol_Position_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.PositionOuterClass.Position.class, protocol.PositionOuterClass.Position.Builder.class);
      }

      // Construct using protocol.PositionOuterClass.Position.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getStartFieldBuilder();
          getEndFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        start_ = null;
        if (startBuilder_ != null) {
          startBuilder_.dispose();
          startBuilder_ = null;
        }
        end_ = null;
        if (endBuilder_ != null) {
          endBuilder_.dispose();
          endBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.PositionOuterClass.internal_static_protocol_Position_descriptor;
      }

      @java.lang.Override
      public protocol.PositionOuterClass.Position getDefaultInstanceForType() {
        return protocol.PositionOuterClass.Position.getDefaultInstance();
      }

      @java.lang.Override
      public protocol.PositionOuterClass.Position build() {
        protocol.PositionOuterClass.Position result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protocol.PositionOuterClass.Position buildPartial() {
        protocol.PositionOuterClass.Position result = new protocol.PositionOuterClass.Position(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(protocol.PositionOuterClass.Position result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.start_ = startBuilder_ == null
              ? start_
              : startBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.end_ = endBuilder_ == null
              ? end_
              : endBuilder_.build();
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.PositionOuterClass.Position) {
          return mergeFrom((protocol.PositionOuterClass.Position)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.PositionOuterClass.Position other) {
        if (other == protocol.PositionOuterClass.Position.getDefaultInstance()) return this;
        if (other.hasStart()) {
          mergeStart(other.getStart());
        }
        if (other.hasEnd()) {
          mergeEnd(other.getEnd());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getStartFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    getEndFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private protocol.PositionOuterClass.Point start_;
      private com.google.protobuf.SingleFieldBuilderV3<
          protocol.PositionOuterClass.Point, protocol.PositionOuterClass.Point.Builder, protocol.PositionOuterClass.PointOrBuilder> startBuilder_;
      /**
       * <code>.protocol.Point start = 1;</code>
       * @return Whether the start field is set.
       */
      public boolean hasStart() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.protocol.Point start = 1;</code>
       * @return The start.
       */
      public protocol.PositionOuterClass.Point getStart() {
        if (startBuilder_ == null) {
          return start_ == null ? protocol.PositionOuterClass.Point.getDefaultInstance() : start_;
        } else {
          return startBuilder_.getMessage();
        }
      }
      /**
       * <code>.protocol.Point start = 1;</code>
       */
      public Builder setStart(protocol.PositionOuterClass.Point value) {
        if (startBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          start_ = value;
        } else {
          startBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.protocol.Point start = 1;</code>
       */
      public Builder setStart(
          protocol.PositionOuterClass.Point.Builder builderForValue) {
        if (startBuilder_ == null) {
          start_ = builderForValue.build();
        } else {
          startBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.protocol.Point start = 1;</code>
       */
      public Builder mergeStart(protocol.PositionOuterClass.Point value) {
        if (startBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            start_ != null &&
            start_ != protocol.PositionOuterClass.Point.getDefaultInstance()) {
            getStartBuilder().mergeFrom(value);
          } else {
            start_ = value;
          }
        } else {
          startBuilder_.mergeFrom(value);
        }
        if (start_ != null) {
          bitField0_ |= 0x00000001;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.protocol.Point start = 1;</code>
       */
      public Builder clearStart() {
        bitField0_ = (bitField0_ & ~0x00000001);
        start_ = null;
        if (startBuilder_ != null) {
          startBuilder_.dispose();
          startBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.protocol.Point start = 1;</code>
       */
      public protocol.PositionOuterClass.Point.Builder getStartBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getStartFieldBuilder().getBuilder();
      }
      /**
       * <code>.protocol.Point start = 1;</code>
       */
      public protocol.PositionOuterClass.PointOrBuilder getStartOrBuilder() {
        if (startBuilder_ != null) {
          return startBuilder_.getMessageOrBuilder();
        } else {
          return start_ == null ?
              protocol.PositionOuterClass.Point.getDefaultInstance() : start_;
        }
      }
      /**
       * <code>.protocol.Point start = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          protocol.PositionOuterClass.Point, protocol.PositionOuterClass.Point.Builder, protocol.PositionOuterClass.PointOrBuilder> 
          getStartFieldBuilder() {
        if (startBuilder_ == null) {
          startBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              protocol.PositionOuterClass.Point, protocol.PositionOuterClass.Point.Builder, protocol.PositionOuterClass.PointOrBuilder>(
                  getStart(),
                  getParentForChildren(),
                  isClean());
          start_ = null;
        }
        return startBuilder_;
      }

      private protocol.PositionOuterClass.Point end_;
      private com.google.protobuf.SingleFieldBuilderV3<
          protocol.PositionOuterClass.Point, protocol.PositionOuterClass.Point.Builder, protocol.PositionOuterClass.PointOrBuilder> endBuilder_;
      /**
       * <code>.protocol.Point end = 2;</code>
       * @return Whether the end field is set.
       */
      public boolean hasEnd() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>.protocol.Point end = 2;</code>
       * @return The end.
       */
      public protocol.PositionOuterClass.Point getEnd() {
        if (endBuilder_ == null) {
          return end_ == null ? protocol.PositionOuterClass.Point.getDefaultInstance() : end_;
        } else {
          return endBuilder_.getMessage();
        }
      }
      /**
       * <code>.protocol.Point end = 2;</code>
       */
      public Builder setEnd(protocol.PositionOuterClass.Point value) {
        if (endBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          end_ = value;
        } else {
          endBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.protocol.Point end = 2;</code>
       */
      public Builder setEnd(
          protocol.PositionOuterClass.Point.Builder builderForValue) {
        if (endBuilder_ == null) {
          end_ = builderForValue.build();
        } else {
          endBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.protocol.Point end = 2;</code>
       */
      public Builder mergeEnd(protocol.PositionOuterClass.Point value) {
        if (endBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            end_ != null &&
            end_ != protocol.PositionOuterClass.Point.getDefaultInstance()) {
            getEndBuilder().mergeFrom(value);
          } else {
            end_ = value;
          }
        } else {
          endBuilder_.mergeFrom(value);
        }
        if (end_ != null) {
          bitField0_ |= 0x00000002;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.protocol.Point end = 2;</code>
       */
      public Builder clearEnd() {
        bitField0_ = (bitField0_ & ~0x00000002);
        end_ = null;
        if (endBuilder_ != null) {
          endBuilder_.dispose();
          endBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.protocol.Point end = 2;</code>
       */
      public protocol.PositionOuterClass.Point.Builder getEndBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getEndFieldBuilder().getBuilder();
      }
      /**
       * <code>.protocol.Point end = 2;</code>
       */
      public protocol.PositionOuterClass.PointOrBuilder getEndOrBuilder() {
        if (endBuilder_ != null) {
          return endBuilder_.getMessageOrBuilder();
        } else {
          return end_ == null ?
              protocol.PositionOuterClass.Point.getDefaultInstance() : end_;
        }
      }
      /**
       * <code>.protocol.Point end = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          protocol.PositionOuterClass.Point, protocol.PositionOuterClass.Point.Builder, protocol.PositionOuterClass.PointOrBuilder> 
          getEndFieldBuilder() {
        if (endBuilder_ == null) {
          endBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              protocol.PositionOuterClass.Point, protocol.PositionOuterClass.Point.Builder, protocol.PositionOuterClass.PointOrBuilder>(
                  getEnd(),
                  getParentForChildren(),
                  isClean());
          end_ = null;
        }
        return endBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.Position)
    }

    // @@protoc_insertion_point(class_scope:protocol.Position)
    private static final protocol.PositionOuterClass.Position DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocol.PositionOuterClass.Position();
    }

    public static protocol.PositionOuterClass.Position getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Position>
        PARSER = new com.google.protobuf.AbstractParser<Position>() {
      @java.lang.Override
      public Position parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Position> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Position> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protocol.PositionOuterClass.Position getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PointOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.Point)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 line = 1;</code>
     * @return The line.
     */
    int getLine();

    /**
     * <code>int32 column = 2;</code>
     * @return The column.
     */
    int getColumn();
  }
  /**
   * Protobuf type {@code protocol.Point}
   */
  public static final class Point extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol.Point)
      PointOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Point.newBuilder() to construct.
    private Point(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Point() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Point();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.PositionOuterClass.internal_static_protocol_Point_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.PositionOuterClass.internal_static_protocol_Point_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.PositionOuterClass.Point.class, protocol.PositionOuterClass.Point.Builder.class);
    }

    public static final int LINE_FIELD_NUMBER = 1;
    private int line_ = 0;
    /**
     * <code>int32 line = 1;</code>
     * @return The line.
     */
    @java.lang.Override
    public int getLine() {
      return line_;
    }

    public static final int COLUMN_FIELD_NUMBER = 2;
    private int column_ = 0;
    /**
     * <code>int32 column = 2;</code>
     * @return The column.
     */
    @java.lang.Override
    public int getColumn() {
      return column_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (line_ != 0) {
        output.writeInt32(1, line_);
      }
      if (column_ != 0) {
        output.writeInt32(2, column_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (line_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, line_);
      }
      if (column_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, column_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protocol.PositionOuterClass.Point)) {
        return super.equals(obj);
      }
      protocol.PositionOuterClass.Point other = (protocol.PositionOuterClass.Point) obj;

      if (getLine()
          != other.getLine()) return false;
      if (getColumn()
          != other.getColumn()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LINE_FIELD_NUMBER;
      hash = (53 * hash) + getLine();
      hash = (37 * hash) + COLUMN_FIELD_NUMBER;
      hash = (53 * hash) + getColumn();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protocol.PositionOuterClass.Point parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.PositionOuterClass.Point parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.PositionOuterClass.Point parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.PositionOuterClass.Point parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.PositionOuterClass.Point parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.PositionOuterClass.Point parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.PositionOuterClass.Point parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.PositionOuterClass.Point parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static protocol.PositionOuterClass.Point parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static protocol.PositionOuterClass.Point parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.PositionOuterClass.Point parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.PositionOuterClass.Point parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocol.PositionOuterClass.Point prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.Point}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.Point)
        protocol.PositionOuterClass.PointOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.PositionOuterClass.internal_static_protocol_Point_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.PositionOuterClass.internal_static_protocol_Point_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.PositionOuterClass.Point.class, protocol.PositionOuterClass.Point.Builder.class);
      }

      // Construct using protocol.PositionOuterClass.Point.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        line_ = 0;
        column_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.PositionOuterClass.internal_static_protocol_Point_descriptor;
      }

      @java.lang.Override
      public protocol.PositionOuterClass.Point getDefaultInstanceForType() {
        return protocol.PositionOuterClass.Point.getDefaultInstance();
      }

      @java.lang.Override
      public protocol.PositionOuterClass.Point build() {
        protocol.PositionOuterClass.Point result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protocol.PositionOuterClass.Point buildPartial() {
        protocol.PositionOuterClass.Point result = new protocol.PositionOuterClass.Point(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(protocol.PositionOuterClass.Point result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.line_ = line_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.column_ = column_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.PositionOuterClass.Point) {
          return mergeFrom((protocol.PositionOuterClass.Point)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.PositionOuterClass.Point other) {
        if (other == protocol.PositionOuterClass.Point.getDefaultInstance()) return this;
        if (other.getLine() != 0) {
          setLine(other.getLine());
        }
        if (other.getColumn() != 0) {
          setColumn(other.getColumn());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                line_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                column_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int line_ ;
      /**
       * <code>int32 line = 1;</code>
       * @return The line.
       */
      @java.lang.Override
      public int getLine() {
        return line_;
      }
      /**
       * <code>int32 line = 1;</code>
       * @param value The line to set.
       * @return This builder for chaining.
       */
      public Builder setLine(int value) {

        line_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 line = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearLine() {
        bitField0_ = (bitField0_ & ~0x00000001);
        line_ = 0;
        onChanged();
        return this;
      }

      private int column_ ;
      /**
       * <code>int32 column = 2;</code>
       * @return The column.
       */
      @java.lang.Override
      public int getColumn() {
        return column_;
      }
      /**
       * <code>int32 column = 2;</code>
       * @param value The column to set.
       * @return This builder for chaining.
       */
      public Builder setColumn(int value) {

        column_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 column = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearColumn() {
        bitField0_ = (bitField0_ & ~0x00000002);
        column_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.Point)
    }

    // @@protoc_insertion_point(class_scope:protocol.Point)
    private static final protocol.PositionOuterClass.Point DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocol.PositionOuterClass.Point();
    }

    public static protocol.PositionOuterClass.Point getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Point>
        PARSER = new com.google.protobuf.AbstractParser<Point>() {
      @java.lang.Override
      public Point parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Point> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Point> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protocol.PositionOuterClass.Point getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_Position_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_Position_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_Point_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_Point_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016position.proto\022\010protocol\"H\n\010Position\022\036" +
      "\n\005start\030\001 \001(\0132\017.protocol.Point\022\034\n\003end\030\002 " +
      "\001(\0132\017.protocol.Point\"%\n\005Point\022\014\n\004line\030\001 " +
      "\001(\005\022\016\n\006column\030\002 \001(\005b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protocol_Position_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_Position_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_Position_descriptor,
        new java.lang.String[] { "Start", "End", });
    internal_static_protocol_Point_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protocol_Point_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_Point_descriptor,
        new java.lang.String[] { "Line", "Column", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
