// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: response.proto

// Protobuf Java Version: 3.25.3
package protocol;

public final class Response {
  private Response() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AstResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.AstResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.protocol.ProgramFile program = 1;</code>
     * @return Whether the program field is set.
     */
    boolean hasProgram();
    /**
     * <code>.protocol.ProgramFile program = 1;</code>
     * @return The program.
     */
    protocol.Base.ProgramFile getProgram();
    /**
     * <code>.protocol.ProgramFile program = 1;</code>
     */
    protocol.Base.ProgramFileOrBuilder getProgramOrBuilder();

    /**
     * <code>repeated .protocol.LanguageError errors = 2;</code>
     */
    java.util.List<protocol.Response.LanguageError> 
        getErrorsList();
    /**
     * <code>repeated .protocol.LanguageError errors = 2;</code>
     */
    protocol.Response.LanguageError getErrors(int index);
    /**
     * <code>repeated .protocol.LanguageError errors = 2;</code>
     */
    int getErrorsCount();
    /**
     * <code>repeated .protocol.LanguageError errors = 2;</code>
     */
    java.util.List<? extends protocol.Response.LanguageErrorOrBuilder> 
        getErrorsOrBuilderList();
    /**
     * <code>repeated .protocol.LanguageError errors = 2;</code>
     */
    protocol.Response.LanguageErrorOrBuilder getErrorsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code protocol.AstResponse}
   */
  public static final class AstResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol.AstResponse)
      AstResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AstResponse.newBuilder() to construct.
    private AstResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AstResponse() {
      errors_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AstResponse();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.Response.internal_static_protocol_AstResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.Response.internal_static_protocol_AstResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.Response.AstResponse.class, protocol.Response.AstResponse.Builder.class);
    }

    private int bitField0_;
    public static final int PROGRAM_FIELD_NUMBER = 1;
    private protocol.Base.ProgramFile program_;
    /**
     * <code>.protocol.ProgramFile program = 1;</code>
     * @return Whether the program field is set.
     */
    @java.lang.Override
    public boolean hasProgram() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.protocol.ProgramFile program = 1;</code>
     * @return The program.
     */
    @java.lang.Override
    public protocol.Base.ProgramFile getProgram() {
      return program_ == null ? protocol.Base.ProgramFile.getDefaultInstance() : program_;
    }
    /**
     * <code>.protocol.ProgramFile program = 1;</code>
     */
    @java.lang.Override
    public protocol.Base.ProgramFileOrBuilder getProgramOrBuilder() {
      return program_ == null ? protocol.Base.ProgramFile.getDefaultInstance() : program_;
    }

    public static final int ERRORS_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private java.util.List<protocol.Response.LanguageError> errors_;
    /**
     * <code>repeated .protocol.LanguageError errors = 2;</code>
     */
    @java.lang.Override
    public java.util.List<protocol.Response.LanguageError> getErrorsList() {
      return errors_;
    }
    /**
     * <code>repeated .protocol.LanguageError errors = 2;</code>
     */
    @java.lang.Override
    public java.util.List<? extends protocol.Response.LanguageErrorOrBuilder> 
        getErrorsOrBuilderList() {
      return errors_;
    }
    /**
     * <code>repeated .protocol.LanguageError errors = 2;</code>
     */
    @java.lang.Override
    public int getErrorsCount() {
      return errors_.size();
    }
    /**
     * <code>repeated .protocol.LanguageError errors = 2;</code>
     */
    @java.lang.Override
    public protocol.Response.LanguageError getErrors(int index) {
      return errors_.get(index);
    }
    /**
     * <code>repeated .protocol.LanguageError errors = 2;</code>
     */
    @java.lang.Override
    public protocol.Response.LanguageErrorOrBuilder getErrorsOrBuilder(
        int index) {
      return errors_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getProgram());
      }
      for (int i = 0; i < errors_.size(); i++) {
        output.writeMessage(2, errors_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getProgram());
      }
      for (int i = 0; i < errors_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, errors_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protocol.Response.AstResponse)) {
        return super.equals(obj);
      }
      protocol.Response.AstResponse other = (protocol.Response.AstResponse) obj;

      if (hasProgram() != other.hasProgram()) return false;
      if (hasProgram()) {
        if (!getProgram()
            .equals(other.getProgram())) return false;
      }
      if (!getErrorsList()
          .equals(other.getErrorsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasProgram()) {
        hash = (37 * hash) + PROGRAM_FIELD_NUMBER;
        hash = (53 * hash) + getProgram().hashCode();
      }
      if (getErrorsCount() > 0) {
        hash = (37 * hash) + ERRORS_FIELD_NUMBER;
        hash = (53 * hash) + getErrorsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protocol.Response.AstResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Response.AstResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Response.AstResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Response.AstResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Response.AstResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Response.AstResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Response.AstResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.Response.AstResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static protocol.Response.AstResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static protocol.Response.AstResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.Response.AstResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.Response.AstResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocol.Response.AstResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.AstResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.AstResponse)
        protocol.Response.AstResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.Response.internal_static_protocol_AstResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.Response.internal_static_protocol_AstResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.Response.AstResponse.class, protocol.Response.AstResponse.Builder.class);
      }

      // Construct using protocol.Response.AstResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getProgramFieldBuilder();
          getErrorsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        program_ = null;
        if (programBuilder_ != null) {
          programBuilder_.dispose();
          programBuilder_ = null;
        }
        if (errorsBuilder_ == null) {
          errors_ = java.util.Collections.emptyList();
        } else {
          errors_ = null;
          errorsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.Response.internal_static_protocol_AstResponse_descriptor;
      }

      @java.lang.Override
      public protocol.Response.AstResponse getDefaultInstanceForType() {
        return protocol.Response.AstResponse.getDefaultInstance();
      }

      @java.lang.Override
      public protocol.Response.AstResponse build() {
        protocol.Response.AstResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protocol.Response.AstResponse buildPartial() {
        protocol.Response.AstResponse result = new protocol.Response.AstResponse(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(protocol.Response.AstResponse result) {
        if (errorsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            errors_ = java.util.Collections.unmodifiableList(errors_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.errors_ = errors_;
        } else {
          result.errors_ = errorsBuilder_.build();
        }
      }

      private void buildPartial0(protocol.Response.AstResponse result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.program_ = programBuilder_ == null
              ? program_
              : programBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.Response.AstResponse) {
          return mergeFrom((protocol.Response.AstResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.Response.AstResponse other) {
        if (other == protocol.Response.AstResponse.getDefaultInstance()) return this;
        if (other.hasProgram()) {
          mergeProgram(other.getProgram());
        }
        if (errorsBuilder_ == null) {
          if (!other.errors_.isEmpty()) {
            if (errors_.isEmpty()) {
              errors_ = other.errors_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureErrorsIsMutable();
              errors_.addAll(other.errors_);
            }
            onChanged();
          }
        } else {
          if (!other.errors_.isEmpty()) {
            if (errorsBuilder_.isEmpty()) {
              errorsBuilder_.dispose();
              errorsBuilder_ = null;
              errors_ = other.errors_;
              bitField0_ = (bitField0_ & ~0x00000002);
              errorsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getErrorsFieldBuilder() : null;
            } else {
              errorsBuilder_.addAllMessages(other.errors_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getProgramFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                protocol.Response.LanguageError m =
                    input.readMessage(
                        protocol.Response.LanguageError.parser(),
                        extensionRegistry);
                if (errorsBuilder_ == null) {
                  ensureErrorsIsMutable();
                  errors_.add(m);
                } else {
                  errorsBuilder_.addMessage(m);
                }
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private protocol.Base.ProgramFile program_;
      private com.google.protobuf.SingleFieldBuilderV3<
          protocol.Base.ProgramFile, protocol.Base.ProgramFile.Builder, protocol.Base.ProgramFileOrBuilder> programBuilder_;
      /**
       * <code>.protocol.ProgramFile program = 1;</code>
       * @return Whether the program field is set.
       */
      public boolean hasProgram() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.protocol.ProgramFile program = 1;</code>
       * @return The program.
       */
      public protocol.Base.ProgramFile getProgram() {
        if (programBuilder_ == null) {
          return program_ == null ? protocol.Base.ProgramFile.getDefaultInstance() : program_;
        } else {
          return programBuilder_.getMessage();
        }
      }
      /**
       * <code>.protocol.ProgramFile program = 1;</code>
       */
      public Builder setProgram(protocol.Base.ProgramFile value) {
        if (programBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          program_ = value;
        } else {
          programBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.protocol.ProgramFile program = 1;</code>
       */
      public Builder setProgram(
          protocol.Base.ProgramFile.Builder builderForValue) {
        if (programBuilder_ == null) {
          program_ = builderForValue.build();
        } else {
          programBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.protocol.ProgramFile program = 1;</code>
       */
      public Builder mergeProgram(protocol.Base.ProgramFile value) {
        if (programBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            program_ != null &&
            program_ != protocol.Base.ProgramFile.getDefaultInstance()) {
            getProgramBuilder().mergeFrom(value);
          } else {
            program_ = value;
          }
        } else {
          programBuilder_.mergeFrom(value);
        }
        if (program_ != null) {
          bitField0_ |= 0x00000001;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.protocol.ProgramFile program = 1;</code>
       */
      public Builder clearProgram() {
        bitField0_ = (bitField0_ & ~0x00000001);
        program_ = null;
        if (programBuilder_ != null) {
          programBuilder_.dispose();
          programBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.protocol.ProgramFile program = 1;</code>
       */
      public protocol.Base.ProgramFile.Builder getProgramBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getProgramFieldBuilder().getBuilder();
      }
      /**
       * <code>.protocol.ProgramFile program = 1;</code>
       */
      public protocol.Base.ProgramFileOrBuilder getProgramOrBuilder() {
        if (programBuilder_ != null) {
          return programBuilder_.getMessageOrBuilder();
        } else {
          return program_ == null ?
              protocol.Base.ProgramFile.getDefaultInstance() : program_;
        }
      }
      /**
       * <code>.protocol.ProgramFile program = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          protocol.Base.ProgramFile, protocol.Base.ProgramFile.Builder, protocol.Base.ProgramFileOrBuilder> 
          getProgramFieldBuilder() {
        if (programBuilder_ == null) {
          programBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              protocol.Base.ProgramFile, protocol.Base.ProgramFile.Builder, protocol.Base.ProgramFileOrBuilder>(
                  getProgram(),
                  getParentForChildren(),
                  isClean());
          program_ = null;
        }
        return programBuilder_;
      }

      private java.util.List<protocol.Response.LanguageError> errors_ =
        java.util.Collections.emptyList();
      private void ensureErrorsIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          errors_ = new java.util.ArrayList<protocol.Response.LanguageError>(errors_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          protocol.Response.LanguageError, protocol.Response.LanguageError.Builder, protocol.Response.LanguageErrorOrBuilder> errorsBuilder_;

      /**
       * <code>repeated .protocol.LanguageError errors = 2;</code>
       */
      public java.util.List<protocol.Response.LanguageError> getErrorsList() {
        if (errorsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(errors_);
        } else {
          return errorsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protocol.LanguageError errors = 2;</code>
       */
      public int getErrorsCount() {
        if (errorsBuilder_ == null) {
          return errors_.size();
        } else {
          return errorsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protocol.LanguageError errors = 2;</code>
       */
      public protocol.Response.LanguageError getErrors(int index) {
        if (errorsBuilder_ == null) {
          return errors_.get(index);
        } else {
          return errorsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protocol.LanguageError errors = 2;</code>
       */
      public Builder setErrors(
          int index, protocol.Response.LanguageError value) {
        if (errorsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureErrorsIsMutable();
          errors_.set(index, value);
          onChanged();
        } else {
          errorsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protocol.LanguageError errors = 2;</code>
       */
      public Builder setErrors(
          int index, protocol.Response.LanguageError.Builder builderForValue) {
        if (errorsBuilder_ == null) {
          ensureErrorsIsMutable();
          errors_.set(index, builderForValue.build());
          onChanged();
        } else {
          errorsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protocol.LanguageError errors = 2;</code>
       */
      public Builder addErrors(protocol.Response.LanguageError value) {
        if (errorsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureErrorsIsMutable();
          errors_.add(value);
          onChanged();
        } else {
          errorsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protocol.LanguageError errors = 2;</code>
       */
      public Builder addErrors(
          int index, protocol.Response.LanguageError value) {
        if (errorsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureErrorsIsMutable();
          errors_.add(index, value);
          onChanged();
        } else {
          errorsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protocol.LanguageError errors = 2;</code>
       */
      public Builder addErrors(
          protocol.Response.LanguageError.Builder builderForValue) {
        if (errorsBuilder_ == null) {
          ensureErrorsIsMutable();
          errors_.add(builderForValue.build());
          onChanged();
        } else {
          errorsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protocol.LanguageError errors = 2;</code>
       */
      public Builder addErrors(
          int index, protocol.Response.LanguageError.Builder builderForValue) {
        if (errorsBuilder_ == null) {
          ensureErrorsIsMutable();
          errors_.add(index, builderForValue.build());
          onChanged();
        } else {
          errorsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protocol.LanguageError errors = 2;</code>
       */
      public Builder addAllErrors(
          java.lang.Iterable<? extends protocol.Response.LanguageError> values) {
        if (errorsBuilder_ == null) {
          ensureErrorsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, errors_);
          onChanged();
        } else {
          errorsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protocol.LanguageError errors = 2;</code>
       */
      public Builder clearErrors() {
        if (errorsBuilder_ == null) {
          errors_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          errorsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protocol.LanguageError errors = 2;</code>
       */
      public Builder removeErrors(int index) {
        if (errorsBuilder_ == null) {
          ensureErrorsIsMutable();
          errors_.remove(index);
          onChanged();
        } else {
          errorsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protocol.LanguageError errors = 2;</code>
       */
      public protocol.Response.LanguageError.Builder getErrorsBuilder(
          int index) {
        return getErrorsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protocol.LanguageError errors = 2;</code>
       */
      public protocol.Response.LanguageErrorOrBuilder getErrorsOrBuilder(
          int index) {
        if (errorsBuilder_ == null) {
          return errors_.get(index);  } else {
          return errorsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protocol.LanguageError errors = 2;</code>
       */
      public java.util.List<? extends protocol.Response.LanguageErrorOrBuilder> 
           getErrorsOrBuilderList() {
        if (errorsBuilder_ != null) {
          return errorsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(errors_);
        }
      }
      /**
       * <code>repeated .protocol.LanguageError errors = 2;</code>
       */
      public protocol.Response.LanguageError.Builder addErrorsBuilder() {
        return getErrorsFieldBuilder().addBuilder(
            protocol.Response.LanguageError.getDefaultInstance());
      }
      /**
       * <code>repeated .protocol.LanguageError errors = 2;</code>
       */
      public protocol.Response.LanguageError.Builder addErrorsBuilder(
          int index) {
        return getErrorsFieldBuilder().addBuilder(
            index, protocol.Response.LanguageError.getDefaultInstance());
      }
      /**
       * <code>repeated .protocol.LanguageError errors = 2;</code>
       */
      public java.util.List<protocol.Response.LanguageError.Builder> 
           getErrorsBuilderList() {
        return getErrorsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          protocol.Response.LanguageError, protocol.Response.LanguageError.Builder, protocol.Response.LanguageErrorOrBuilder> 
          getErrorsFieldBuilder() {
        if (errorsBuilder_ == null) {
          errorsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              protocol.Response.LanguageError, protocol.Response.LanguageError.Builder, protocol.Response.LanguageErrorOrBuilder>(
                  errors_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          errors_ = null;
        }
        return errorsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.AstResponse)
    }

    // @@protoc_insertion_point(class_scope:protocol.AstResponse)
    private static final protocol.Response.AstResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocol.Response.AstResponse();
    }

    public static protocol.Response.AstResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AstResponse>
        PARSER = new com.google.protobuf.AbstractParser<AstResponse>() {
      @java.lang.Override
      public AstResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<AstResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AstResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protocol.Response.AstResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LanguageErrorOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.LanguageError)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string message = 1;</code>
     * @return The message.
     */
    java.lang.String getMessage();
    /**
     * <code>string message = 1;</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();

    /**
     * <code>.protocol.Point position = 2;</code>
     * @return Whether the position field is set.
     */
    boolean hasPosition();
    /**
     * <code>.protocol.Point position = 2;</code>
     * @return The position.
     */
    protocol.PositionOuterClass.Point getPosition();
    /**
     * <code>.protocol.Point position = 2;</code>
     */
    protocol.PositionOuterClass.PointOrBuilder getPositionOrBuilder();
  }
  /**
   * Protobuf type {@code protocol.LanguageError}
   */
  public static final class LanguageError extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol.LanguageError)
      LanguageErrorOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LanguageError.newBuilder() to construct.
    private LanguageError(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LanguageError() {
      message_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new LanguageError();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.Response.internal_static_protocol_LanguageError_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.Response.internal_static_protocol_LanguageError_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.Response.LanguageError.class, protocol.Response.LanguageError.Builder.class);
    }

    private int bitField0_;
    public static final int MESSAGE_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object message_ = "";
    /**
     * <code>string message = 1;</code>
     * @return The message.
     */
    @java.lang.Override
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <code>string message = 1;</code>
     * @return The bytes for message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int POSITION_FIELD_NUMBER = 2;
    private protocol.PositionOuterClass.Point position_;
    /**
     * <code>.protocol.Point position = 2;</code>
     * @return Whether the position field is set.
     */
    @java.lang.Override
    public boolean hasPosition() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.protocol.Point position = 2;</code>
     * @return The position.
     */
    @java.lang.Override
    public protocol.PositionOuterClass.Point getPosition() {
      return position_ == null ? protocol.PositionOuterClass.Point.getDefaultInstance() : position_;
    }
    /**
     * <code>.protocol.Point position = 2;</code>
     */
    @java.lang.Override
    public protocol.PositionOuterClass.PointOrBuilder getPositionOrBuilder() {
      return position_ == null ? protocol.PositionOuterClass.Point.getDefaultInstance() : position_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, message_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(2, getPosition());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, message_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getPosition());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protocol.Response.LanguageError)) {
        return super.equals(obj);
      }
      protocol.Response.LanguageError other = (protocol.Response.LanguageError) obj;

      if (!getMessage()
          .equals(other.getMessage())) return false;
      if (hasPosition() != other.hasPosition()) return false;
      if (hasPosition()) {
        if (!getPosition()
            .equals(other.getPosition())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      if (hasPosition()) {
        hash = (37 * hash) + POSITION_FIELD_NUMBER;
        hash = (53 * hash) + getPosition().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protocol.Response.LanguageError parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Response.LanguageError parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Response.LanguageError parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Response.LanguageError parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Response.LanguageError parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Response.LanguageError parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Response.LanguageError parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.Response.LanguageError parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static protocol.Response.LanguageError parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static protocol.Response.LanguageError parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.Response.LanguageError parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.Response.LanguageError parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocol.Response.LanguageError prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.LanguageError}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.LanguageError)
        protocol.Response.LanguageErrorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.Response.internal_static_protocol_LanguageError_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.Response.internal_static_protocol_LanguageError_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.Response.LanguageError.class, protocol.Response.LanguageError.Builder.class);
      }

      // Construct using protocol.Response.LanguageError.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPositionFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        message_ = "";
        position_ = null;
        if (positionBuilder_ != null) {
          positionBuilder_.dispose();
          positionBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.Response.internal_static_protocol_LanguageError_descriptor;
      }

      @java.lang.Override
      public protocol.Response.LanguageError getDefaultInstanceForType() {
        return protocol.Response.LanguageError.getDefaultInstance();
      }

      @java.lang.Override
      public protocol.Response.LanguageError build() {
        protocol.Response.LanguageError result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protocol.Response.LanguageError buildPartial() {
        protocol.Response.LanguageError result = new protocol.Response.LanguageError(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(protocol.Response.LanguageError result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.message_ = message_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.position_ = positionBuilder_ == null
              ? position_
              : positionBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.Response.LanguageError) {
          return mergeFrom((protocol.Response.LanguageError)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.Response.LanguageError other) {
        if (other == protocol.Response.LanguageError.getDefaultInstance()) return this;
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.hasPosition()) {
          mergePosition(other.getPosition());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                message_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    getPositionFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object message_ = "";
      /**
       * <code>string message = 1;</code>
       * @return The message.
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string message = 1;</code>
       * @return The bytes for message.
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string message = 1;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        message_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string message = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        message_ = getDefaultInstance().getMessage();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string message = 1;</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        message_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private protocol.PositionOuterClass.Point position_;
      private com.google.protobuf.SingleFieldBuilderV3<
          protocol.PositionOuterClass.Point, protocol.PositionOuterClass.Point.Builder, protocol.PositionOuterClass.PointOrBuilder> positionBuilder_;
      /**
       * <code>.protocol.Point position = 2;</code>
       * @return Whether the position field is set.
       */
      public boolean hasPosition() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>.protocol.Point position = 2;</code>
       * @return The position.
       */
      public protocol.PositionOuterClass.Point getPosition() {
        if (positionBuilder_ == null) {
          return position_ == null ? protocol.PositionOuterClass.Point.getDefaultInstance() : position_;
        } else {
          return positionBuilder_.getMessage();
        }
      }
      /**
       * <code>.protocol.Point position = 2;</code>
       */
      public Builder setPosition(protocol.PositionOuterClass.Point value) {
        if (positionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          position_ = value;
        } else {
          positionBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.protocol.Point position = 2;</code>
       */
      public Builder setPosition(
          protocol.PositionOuterClass.Point.Builder builderForValue) {
        if (positionBuilder_ == null) {
          position_ = builderForValue.build();
        } else {
          positionBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.protocol.Point position = 2;</code>
       */
      public Builder mergePosition(protocol.PositionOuterClass.Point value) {
        if (positionBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            position_ != null &&
            position_ != protocol.PositionOuterClass.Point.getDefaultInstance()) {
            getPositionBuilder().mergeFrom(value);
          } else {
            position_ = value;
          }
        } else {
          positionBuilder_.mergeFrom(value);
        }
        if (position_ != null) {
          bitField0_ |= 0x00000002;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.protocol.Point position = 2;</code>
       */
      public Builder clearPosition() {
        bitField0_ = (bitField0_ & ~0x00000002);
        position_ = null;
        if (positionBuilder_ != null) {
          positionBuilder_.dispose();
          positionBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.protocol.Point position = 2;</code>
       */
      public protocol.PositionOuterClass.Point.Builder getPositionBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getPositionFieldBuilder().getBuilder();
      }
      /**
       * <code>.protocol.Point position = 2;</code>
       */
      public protocol.PositionOuterClass.PointOrBuilder getPositionOrBuilder() {
        if (positionBuilder_ != null) {
          return positionBuilder_.getMessageOrBuilder();
        } else {
          return position_ == null ?
              protocol.PositionOuterClass.Point.getDefaultInstance() : position_;
        }
      }
      /**
       * <code>.protocol.Point position = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          protocol.PositionOuterClass.Point, protocol.PositionOuterClass.Point.Builder, protocol.PositionOuterClass.PointOrBuilder> 
          getPositionFieldBuilder() {
        if (positionBuilder_ == null) {
          positionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              protocol.PositionOuterClass.Point, protocol.PositionOuterClass.Point.Builder, protocol.PositionOuterClass.PointOrBuilder>(
                  getPosition(),
                  getParentForChildren(),
                  isClean());
          position_ = null;
        }
        return positionBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.LanguageError)
    }

    // @@protoc_insertion_point(class_scope:protocol.LanguageError)
    private static final protocol.Response.LanguageError DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocol.Response.LanguageError();
    }

    public static protocol.Response.LanguageError getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LanguageError>
        PARSER = new com.google.protobuf.AbstractParser<LanguageError>() {
      @java.lang.Override
      public LanguageError parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<LanguageError> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LanguageError> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protocol.Response.LanguageError getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TranspileResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.TranspileResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string code = 1;</code>
     * @return The code.
     */
    java.lang.String getCode();
    /**
     * <code>string code = 1;</code>
     * @return The bytes for code.
     */
    com.google.protobuf.ByteString
        getCodeBytes();

    /**
     * <code>repeated .protocol.LanguageError errors = 2;</code>
     */
    java.util.List<protocol.Response.LanguageError> 
        getErrorsList();
    /**
     * <code>repeated .protocol.LanguageError errors = 2;</code>
     */
    protocol.Response.LanguageError getErrors(int index);
    /**
     * <code>repeated .protocol.LanguageError errors = 2;</code>
     */
    int getErrorsCount();
    /**
     * <code>repeated .protocol.LanguageError errors = 2;</code>
     */
    java.util.List<? extends protocol.Response.LanguageErrorOrBuilder> 
        getErrorsOrBuilderList();
    /**
     * <code>repeated .protocol.LanguageError errors = 2;</code>
     */
    protocol.Response.LanguageErrorOrBuilder getErrorsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code protocol.TranspileResponse}
   */
  public static final class TranspileResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol.TranspileResponse)
      TranspileResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TranspileResponse.newBuilder() to construct.
    private TranspileResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TranspileResponse() {
      code_ = "";
      errors_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TranspileResponse();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.Response.internal_static_protocol_TranspileResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.Response.internal_static_protocol_TranspileResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.Response.TranspileResponse.class, protocol.Response.TranspileResponse.Builder.class);
    }

    public static final int CODE_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object code_ = "";
    /**
     * <code>string code = 1;</code>
     * @return The code.
     */
    @java.lang.Override
    public java.lang.String getCode() {
      java.lang.Object ref = code_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        code_ = s;
        return s;
      }
    }
    /**
     * <code>string code = 1;</code>
     * @return The bytes for code.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCodeBytes() {
      java.lang.Object ref = code_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        code_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ERRORS_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private java.util.List<protocol.Response.LanguageError> errors_;
    /**
     * <code>repeated .protocol.LanguageError errors = 2;</code>
     */
    @java.lang.Override
    public java.util.List<protocol.Response.LanguageError> getErrorsList() {
      return errors_;
    }
    /**
     * <code>repeated .protocol.LanguageError errors = 2;</code>
     */
    @java.lang.Override
    public java.util.List<? extends protocol.Response.LanguageErrorOrBuilder> 
        getErrorsOrBuilderList() {
      return errors_;
    }
    /**
     * <code>repeated .protocol.LanguageError errors = 2;</code>
     */
    @java.lang.Override
    public int getErrorsCount() {
      return errors_.size();
    }
    /**
     * <code>repeated .protocol.LanguageError errors = 2;</code>
     */
    @java.lang.Override
    public protocol.Response.LanguageError getErrors(int index) {
      return errors_.get(index);
    }
    /**
     * <code>repeated .protocol.LanguageError errors = 2;</code>
     */
    @java.lang.Override
    public protocol.Response.LanguageErrorOrBuilder getErrorsOrBuilder(
        int index) {
      return errors_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(code_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, code_);
      }
      for (int i = 0; i < errors_.size(); i++) {
        output.writeMessage(2, errors_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(code_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, code_);
      }
      for (int i = 0; i < errors_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, errors_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protocol.Response.TranspileResponse)) {
        return super.equals(obj);
      }
      protocol.Response.TranspileResponse other = (protocol.Response.TranspileResponse) obj;

      if (!getCode()
          .equals(other.getCode())) return false;
      if (!getErrorsList()
          .equals(other.getErrorsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode().hashCode();
      if (getErrorsCount() > 0) {
        hash = (37 * hash) + ERRORS_FIELD_NUMBER;
        hash = (53 * hash) + getErrorsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protocol.Response.TranspileResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Response.TranspileResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Response.TranspileResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Response.TranspileResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Response.TranspileResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Response.TranspileResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Response.TranspileResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.Response.TranspileResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static protocol.Response.TranspileResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static protocol.Response.TranspileResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.Response.TranspileResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.Response.TranspileResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocol.Response.TranspileResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.TranspileResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.TranspileResponse)
        protocol.Response.TranspileResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.Response.internal_static_protocol_TranspileResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.Response.internal_static_protocol_TranspileResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.Response.TranspileResponse.class, protocol.Response.TranspileResponse.Builder.class);
      }

      // Construct using protocol.Response.TranspileResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        code_ = "";
        if (errorsBuilder_ == null) {
          errors_ = java.util.Collections.emptyList();
        } else {
          errors_ = null;
          errorsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.Response.internal_static_protocol_TranspileResponse_descriptor;
      }

      @java.lang.Override
      public protocol.Response.TranspileResponse getDefaultInstanceForType() {
        return protocol.Response.TranspileResponse.getDefaultInstance();
      }

      @java.lang.Override
      public protocol.Response.TranspileResponse build() {
        protocol.Response.TranspileResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protocol.Response.TranspileResponse buildPartial() {
        protocol.Response.TranspileResponse result = new protocol.Response.TranspileResponse(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(protocol.Response.TranspileResponse result) {
        if (errorsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            errors_ = java.util.Collections.unmodifiableList(errors_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.errors_ = errors_;
        } else {
          result.errors_ = errorsBuilder_.build();
        }
      }

      private void buildPartial0(protocol.Response.TranspileResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.code_ = code_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.Response.TranspileResponse) {
          return mergeFrom((protocol.Response.TranspileResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.Response.TranspileResponse other) {
        if (other == protocol.Response.TranspileResponse.getDefaultInstance()) return this;
        if (!other.getCode().isEmpty()) {
          code_ = other.code_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (errorsBuilder_ == null) {
          if (!other.errors_.isEmpty()) {
            if (errors_.isEmpty()) {
              errors_ = other.errors_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureErrorsIsMutable();
              errors_.addAll(other.errors_);
            }
            onChanged();
          }
        } else {
          if (!other.errors_.isEmpty()) {
            if (errorsBuilder_.isEmpty()) {
              errorsBuilder_.dispose();
              errorsBuilder_ = null;
              errors_ = other.errors_;
              bitField0_ = (bitField0_ & ~0x00000002);
              errorsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getErrorsFieldBuilder() : null;
            } else {
              errorsBuilder_.addAllMessages(other.errors_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                code_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                protocol.Response.LanguageError m =
                    input.readMessage(
                        protocol.Response.LanguageError.parser(),
                        extensionRegistry);
                if (errorsBuilder_ == null) {
                  ensureErrorsIsMutable();
                  errors_.add(m);
                } else {
                  errorsBuilder_.addMessage(m);
                }
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object code_ = "";
      /**
       * <code>string code = 1;</code>
       * @return The code.
       */
      public java.lang.String getCode() {
        java.lang.Object ref = code_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          code_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string code = 1;</code>
       * @return The bytes for code.
       */
      public com.google.protobuf.ByteString
          getCodeBytes() {
        java.lang.Object ref = code_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          code_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string code = 1;</code>
       * @param value The code to set.
       * @return This builder for chaining.
       */
      public Builder setCode(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        code_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string code = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCode() {
        code_ = getDefaultInstance().getCode();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string code = 1;</code>
       * @param value The bytes for code to set.
       * @return This builder for chaining.
       */
      public Builder setCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        code_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.util.List<protocol.Response.LanguageError> errors_ =
        java.util.Collections.emptyList();
      private void ensureErrorsIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          errors_ = new java.util.ArrayList<protocol.Response.LanguageError>(errors_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          protocol.Response.LanguageError, protocol.Response.LanguageError.Builder, protocol.Response.LanguageErrorOrBuilder> errorsBuilder_;

      /**
       * <code>repeated .protocol.LanguageError errors = 2;</code>
       */
      public java.util.List<protocol.Response.LanguageError> getErrorsList() {
        if (errorsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(errors_);
        } else {
          return errorsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protocol.LanguageError errors = 2;</code>
       */
      public int getErrorsCount() {
        if (errorsBuilder_ == null) {
          return errors_.size();
        } else {
          return errorsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protocol.LanguageError errors = 2;</code>
       */
      public protocol.Response.LanguageError getErrors(int index) {
        if (errorsBuilder_ == null) {
          return errors_.get(index);
        } else {
          return errorsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protocol.LanguageError errors = 2;</code>
       */
      public Builder setErrors(
          int index, protocol.Response.LanguageError value) {
        if (errorsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureErrorsIsMutable();
          errors_.set(index, value);
          onChanged();
        } else {
          errorsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protocol.LanguageError errors = 2;</code>
       */
      public Builder setErrors(
          int index, protocol.Response.LanguageError.Builder builderForValue) {
        if (errorsBuilder_ == null) {
          ensureErrorsIsMutable();
          errors_.set(index, builderForValue.build());
          onChanged();
        } else {
          errorsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protocol.LanguageError errors = 2;</code>
       */
      public Builder addErrors(protocol.Response.LanguageError value) {
        if (errorsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureErrorsIsMutable();
          errors_.add(value);
          onChanged();
        } else {
          errorsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protocol.LanguageError errors = 2;</code>
       */
      public Builder addErrors(
          int index, protocol.Response.LanguageError value) {
        if (errorsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureErrorsIsMutable();
          errors_.add(index, value);
          onChanged();
        } else {
          errorsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protocol.LanguageError errors = 2;</code>
       */
      public Builder addErrors(
          protocol.Response.LanguageError.Builder builderForValue) {
        if (errorsBuilder_ == null) {
          ensureErrorsIsMutable();
          errors_.add(builderForValue.build());
          onChanged();
        } else {
          errorsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protocol.LanguageError errors = 2;</code>
       */
      public Builder addErrors(
          int index, protocol.Response.LanguageError.Builder builderForValue) {
        if (errorsBuilder_ == null) {
          ensureErrorsIsMutable();
          errors_.add(index, builderForValue.build());
          onChanged();
        } else {
          errorsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protocol.LanguageError errors = 2;</code>
       */
      public Builder addAllErrors(
          java.lang.Iterable<? extends protocol.Response.LanguageError> values) {
        if (errorsBuilder_ == null) {
          ensureErrorsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, errors_);
          onChanged();
        } else {
          errorsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protocol.LanguageError errors = 2;</code>
       */
      public Builder clearErrors() {
        if (errorsBuilder_ == null) {
          errors_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          errorsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protocol.LanguageError errors = 2;</code>
       */
      public Builder removeErrors(int index) {
        if (errorsBuilder_ == null) {
          ensureErrorsIsMutable();
          errors_.remove(index);
          onChanged();
        } else {
          errorsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protocol.LanguageError errors = 2;</code>
       */
      public protocol.Response.LanguageError.Builder getErrorsBuilder(
          int index) {
        return getErrorsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protocol.LanguageError errors = 2;</code>
       */
      public protocol.Response.LanguageErrorOrBuilder getErrorsOrBuilder(
          int index) {
        if (errorsBuilder_ == null) {
          return errors_.get(index);  } else {
          return errorsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protocol.LanguageError errors = 2;</code>
       */
      public java.util.List<? extends protocol.Response.LanguageErrorOrBuilder> 
           getErrorsOrBuilderList() {
        if (errorsBuilder_ != null) {
          return errorsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(errors_);
        }
      }
      /**
       * <code>repeated .protocol.LanguageError errors = 2;</code>
       */
      public protocol.Response.LanguageError.Builder addErrorsBuilder() {
        return getErrorsFieldBuilder().addBuilder(
            protocol.Response.LanguageError.getDefaultInstance());
      }
      /**
       * <code>repeated .protocol.LanguageError errors = 2;</code>
       */
      public protocol.Response.LanguageError.Builder addErrorsBuilder(
          int index) {
        return getErrorsFieldBuilder().addBuilder(
            index, protocol.Response.LanguageError.getDefaultInstance());
      }
      /**
       * <code>repeated .protocol.LanguageError errors = 2;</code>
       */
      public java.util.List<protocol.Response.LanguageError.Builder> 
           getErrorsBuilderList() {
        return getErrorsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          protocol.Response.LanguageError, protocol.Response.LanguageError.Builder, protocol.Response.LanguageErrorOrBuilder> 
          getErrorsFieldBuilder() {
        if (errorsBuilder_ == null) {
          errorsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              protocol.Response.LanguageError, protocol.Response.LanguageError.Builder, protocol.Response.LanguageErrorOrBuilder>(
                  errors_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          errors_ = null;
        }
        return errorsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.TranspileResponse)
    }

    // @@protoc_insertion_point(class_scope:protocol.TranspileResponse)
    private static final protocol.Response.TranspileResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocol.Response.TranspileResponse();
    }

    public static protocol.Response.TranspileResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TranspileResponse>
        PARSER = new com.google.protobuf.AbstractParser<TranspileResponse>() {
      @java.lang.Override
      public TranspileResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<TranspileResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TranspileResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protocol.Response.TranspileResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_AstResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_AstResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_LanguageError_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_LanguageError_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_TranspileResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_TranspileResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016response.proto\022\010protocol\032\016position.pro" +
      "to\032\nbase.proto\"^\n\013AstResponse\022&\n\007program" +
      "\030\001 \001(\0132\025.protocol.ProgramFile\022\'\n\006errors\030" +
      "\002 \003(\0132\027.protocol.LanguageError\"C\n\rLangua" +
      "geError\022\017\n\007message\030\001 \001(\t\022!\n\010position\030\002 \001" +
      "(\0132\017.protocol.Point\"J\n\021TranspileResponse" +
      "\022\014\n\004code\030\001 \001(\t\022\'\n\006errors\030\002 \003(\0132\027.protoco" +
      "l.LanguageErrorb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          protocol.PositionOuterClass.getDescriptor(),
          protocol.Base.getDescriptor(),
        });
    internal_static_protocol_AstResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_AstResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_AstResponse_descriptor,
        new java.lang.String[] { "Program", "Errors", });
    internal_static_protocol_LanguageError_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protocol_LanguageError_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_LanguageError_descriptor,
        new java.lang.String[] { "Message", "Position", });
    internal_static_protocol_TranspileResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_protocol_TranspileResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_TranspileResponse_descriptor,
        new java.lang.String[] { "Code", "Errors", });
    protocol.PositionOuterClass.getDescriptor();
    protocol.Base.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
